// Блок 8 — Family. Рассказать, кто есть в семье и какие они.
//
// Грамматика блока — have got: британский способ сказать «у меня есть». Он же
// понадобится дальше для брони, симптомов и вещей в сумке, поэтому вводится здесь, на
// самой безопасной теме, где ошибиться не страшно.

const HG = 'a1-have-got'
const F = 'a1-tema-family'
const B = 'a1-to-be'
const Q = 'a1-questions'
const P = 'a1-pronouns'
const D = 'a1-tema-description'
const PS = 'a1-present-simple'

export default {
  slug: 'family',
  title: 'Family',
  subtitle: 'have got: кто есть в семье, сколько им лет и какие они',
  canDo: [
    'сказать, есть ли у тебя братья и сёстры',
    'назвать возраст и профессию близких',
    'описать человека двумя-тремя словами',
    'спросить о чужой семье, не залезая в личное',
    'показать фотографию и рассказать, кто на ней',
  ],
  lessons: [
    {
      title: 'I have got a sister',
      summary: 'Британское «у меня есть».',
      topics: [HG, F],
      dialogue: ['О семье', [
        ['Anna', 'Have you got brothers or sisters?', 'У тебя есть братья или сёстры?'],
        ['Ben', 'I have got one sister.', 'У меня есть сестра.'],
        ['Anna', 'How old is she?', 'Сколько ей лет?'],
        ['Ben', 'Twenty-five. And you?', 'Двадцать пять. А у тебя?'],
        ['Anna', 'I have got two brothers.', 'У меня два брата.'],
      ]],
      words: [
        ['I have got', 'у меня есть', 'I have got a sister.'],
        ['Have you got…?', 'У тебя есть …?', 'Have you got a car?'],
        ['a family', 'семья', 'A big family.'],
        ['parents', 'родители', 'My parents live here.'],
        ['a son', 'сын', 'My son is five.'],
      ],
      rule: ['Have got и have', 'Британцы говорят I have got a sister, американцы — I have a sister. Смысл один. Вопрос строится по-разному: have you got a sister против do you have a sister, и смешивать половинки нельзя.'],
      quiz: [
        ['«У меня есть сестра» (по-британски) —', ['I have got a sister', 'I have got sister', 'I am have a sister'], 0],
        ['«У тебя есть машина?» —', ['Have you got a car?', 'Do you have got a car?', 'Have you a car got?'], 0],
        ['«Мои родители живут здесь» —', ['My parents live here', 'My parents lives here', 'My parent live here'], 0],
      ],
      order: ['У меня есть сестра.', 'I have got a sister.'],
      produce: [
        ['У меня два брата.', 'I have got two brothers.', ['I have two brothers.']],
        ['У тебя есть сёстры?', 'Have you got sisters?', ['Do you have sisters?']],
        ['Мои родители живут здесь.', 'My parents live here.', []],
      ],
    },
    {
      title: 'This is my family',
      summary: 'Показать фотографию и назвать всех.',
      topics: [F, B, P],
      dialogue: ['Фотография', [
        ['Anna', 'This is my family.', 'Это моя семья.'],
        ['Ben', 'Who is this?', 'А это кто?'],
        ['Anna', 'That is my mother. And this is my father.', 'Это моя мама. А это папа.'],
        ['Ben', 'And the girl?', 'А девочка?'],
        ['Anna', 'That is my daughter. She is seven.', 'Это моя дочь. Ей семь.'],
      ]],
      words: [
        ['a mother', 'мама', 'My mother is a teacher.'],
        ['a father', 'папа', 'My father works here.'],
        ['a daughter', 'дочь', 'My daughter is seven.'],
        ['a girl', 'девочка', 'The girl is my daughter.'],
        ['a boy', 'мальчик', 'The boy is my son.'],
      ],
      rule: ['Mum и dad', 'Mother и father — нейтрально и чуть официально. В обычном разговоре говорят mum и dad (в Америке mom). О чужих родителях вежливее сказать your parents, чем your mum and dad.'],
      quiz: [
        ['«Это моя мама» —', ['This is my mother', 'This is my mother it', 'It is my mother this'], 0],
        ['«А это кто?» —', ['Who is this?', 'Who this is?', 'What is this who?'], 0],
        ['Разговорное «мама» в Британии —', ['mum', 'mom', 'mama'], 0],
      ],
      order: ['Это моя дочь.', 'This is my daughter.'],
      produce: [
        ['Это моя семья.', 'This is my family.', []],
        ['Это мой папа.', 'This is my father.', []],
        ['Ей семь.', 'She is seven.', ["She's seven."]],
      ],
    },
    {
      title: 'He has got blue eyes',
      summary: 'Описать внешность.',
      topics: [HG, D, F],
      dialogue: ['Как он выглядит', [
        ['Ben', 'What does your brother look like?', 'Как выглядит твой брат?'],
        ['Anna', 'He is tall and he has got blue eyes.', 'Он высокий, и у него голубые глаза.'],
        ['Ben', 'Dark hair?', 'Тёмные волосы?'],
        ['Anna', 'No, fair hair. Like our mother.', 'Нет, светлые. Как у мамы.'],
        ['Ben', 'I see.', 'Понятно.'],
      ]],
      words: [
        ['he has got', 'у него есть', 'He has got blue eyes.'],
        ['tall', 'высокий', 'He is tall.'],
        ['hair', 'волосы', 'Dark hair.'],
        ['eyes', 'глаза', 'Blue eyes.'],
        ['What does he look like?', 'Как он выглядит?', 'What does your brother look like?'],
      ],
      rule: ['Внешность: is или has got', 'Рост и общее впечатление — через to be: he is tall, she is young. Части тела и черты — через have got: he has got blue eyes, she has got dark hair. Сказать he is blue eyes нельзя.'],
      quiz: [
        ['«У него голубые глаза» —', ['He has got blue eyes', 'He is blue eyes', 'He have got blue eyes'], 0],
        ['«Она высокая» —', ['She is tall', 'She has got tall', 'She is a tall'], 0],
        ['«Как он выглядит?» —', ['What does he look like?', 'How does he look like?', 'What he looks like?'], 0],
      ],
      order: ['У него голубые глаза.', 'He has got blue eyes.'],
      produce: [
        ['Он высокий.', 'He is tall.', ["He's tall."]],
        ['У неё тёмные волосы.', 'She has got dark hair.', []],
        ['Как выглядит твой брат?', 'What does your brother look like?', []],
      ],
    },
    {
      title: 'She is kind',
      summary: 'Описать характер, а не внешность.',
      topics: [D, F, B],
      dialogue: ['Какая она', [
        ['Ben', 'What is your sister like?', 'Какая твоя сестра?'],
        ['Anna', 'She is kind and very funny.', 'Добрая и очень весёлая.'],
        ['Ben', 'And your brother?', 'А брат?'],
        ['Anna', 'Quiet, but a good friend.', 'Тихий, но хороший друг.'],
        ['Ben', 'Nice family.', 'Хорошая семья.'],
      ]],
      words: [
        ['kind', 'добрый', 'She is very kind.'],
        ['funny', 'весёлый, смешной', 'He is funny.'],
        ['serious', 'серьёзный', 'She is serious at work.'],
        ['What is she like?', 'Какая она?', 'What is your sister like?'],
        ['young', 'молодой', 'My brother is young.'],
      ],
      rule: ['Два похожих вопроса', 'What is she like — о характере: какая она. What does she look like — о внешности: как выглядит. Различаются одним словом look, и перепутать их — значит получить ответ не о том.'],
      quiz: [
        ['Спрашиваете о характере:', ['What is she like?', 'What does she look like?', 'How is she like?'], 0],
        ['«Она добрая» —', ['She is kind', 'She has kind', 'She is a kind'], 0],
        ['«Тихий, но хороший друг» —', ['Quiet, but a good friend', 'Quiet, but good a friend', 'Quiet, but is good friend'], 0],
      ],
      order: ['Она добрая и очень весёлая.', 'She is kind and very funny.'],
      produce: [
        ['Какая твоя сестра?', 'What is your sister like?', ["What's your sister like?"]],
        ['Он весёлый.', 'He is funny.', ["He's funny."]],
        ['Она серьёзная на работе.', 'She is serious at work.', []],
      ],
    },
    {
      title: 'Have you got children?',
      summary: 'Вопрос о детях — и как на него ответить.',
      topics: [HG, F, Q],
      dialogue: ['Разговор в поезде', [
        ['Соседка', 'Have you got children?', 'У вас есть дети?'],
        ['Ben', 'Yes, I have got a son.', 'Да, у меня сын.'],
        ['Соседка', 'How old is he?', 'Сколько ему?'],
        ['Ben', 'Four. And you?', 'Четыре. А у вас?'],
        ['Соседка', 'No, I have not got children.', 'Нет, детей нет.'],
      ]],
      words: [
        ['I have not got', 'у меня нет', 'I have not got a car.'],
        ['Yes, I have.', 'Да, есть.', 'Have you got a pen? — Yes, I have.'],
        ['No, I have not.', 'Нет.', 'Have you got time? — No, I have not.'],
        ['a grandmother', 'бабушка', 'My grandmother is eighty.'],
        ['a husband', 'муж', 'Her husband is a doctor.'],
      ],
      rule: ['Короткий ответ на have you got', 'Отвечают тем же глаголом: yes, I have — no, I have not. В речи сокращают: haven\'t. Ответ yes, I do здесь не подходит: он относится к вопросам с do you have.'],
      quiz: [
        ['Короткий ответ на have you got:', ['Yes, I have', 'Yes, I do', 'Yes, I am'], 0],
        ['«У меня нет машины» —', ['I have not got a car', 'I have got not a car', 'I not have got a car'], 0],
        ['«Её муж — врач» —', ['Her husband is a doctor', 'Her husband is doctor', 'She husband is a doctor'], 0],
      ],
      order: ['У меня нет машины.', 'I have not got a car.'],
      produce: [
        ['У вас есть дети?', 'Have you got children?', ['Do you have children?']],
        ['Да, у меня сын.', 'Yes, I have got a son.', ['Yes, I have a son.']],
        ['Моей бабушке восемьдесят.', 'My grandmother is eighty.', []],
      ],
    },
    {
      title: 'My brother works in a bank',
      summary: 'Рассказать, чем занимаются близкие: третье лицо.',
      topics: [PS, F],
      dialogue: ['Кто чем занят', [
        ['Anna', 'What does your sister do?', 'Кем работает твоя сестра?'],
        ['Ben', 'She works in a school. She is a teacher.', 'Она работает в школе. Учительница.'],
        ['Anna', 'And your brother?', 'А брат?'],
        ['Ben', 'He works in a bank.', 'Он работает в банке.'],
        ['Anna', 'A big family of workers!', 'Целая трудовая семья!'],
      ]],
      words: [
        ['he works', 'он работает', 'He works in a bank.'],
        ['she lives', 'она живёт', 'She lives in London.'],
        ['a school', 'школа', 'She works in a school.'],
        ['What does she do?', 'Кем она работает?', 'What does your sister do?'],
        ['a worker', 'работник', 'A family of workers.'],
      ],
      rule: ['То самое -s', 'С he, she, it глагол получает -s: he works, she lives, it costs. Это единственное окончание в настоящем времени, и теряют его чаще всего именно потому, что в русском ничего похожего нет.'],
      quiz: [
        ['«Он работает в банке» —', ['He works in a bank', 'He work in a bank', 'He is work in a bank'], 0],
        ['«Она живёт в Лондоне» —', ['She lives in London', 'She live in London', 'She living in London'], 0],
        ['«Кем работает твоя сестра?» —', ['What does your sister do?', 'What do your sister?', 'What does your sister does?'], 0],
      ],
      order: ['Он работает в банке.', 'He works in a bank.'],
      produce: [
        ['Она работает в школе.', 'She works in a school.', []],
        ['Он живёт в Лондоне.', 'He lives in London.', []],
        ['Кем работает твой брат?', 'What does your brother do?', []],
      ],
    },
    {
      title: 'Our and their',
      summary: 'Общее и чужое: our, their.',
      topics: [P, F],
      dialogue: ['Наши и их', [
        ['Anna', 'This is our house.', 'Это наш дом.'],
        ['Ben', 'And that one?', 'А тот?'],
        ['Anna', 'That is their house. Our neighbours.', 'Тот их. Наши соседи.'],
        ['Ben', 'Are they nice?', 'Они хорошие?'],
        ['Anna', 'Very. Their children play with mine.', 'Очень. Их дети играют с моими.'],
      ]],
      words: [
        ['our', 'наш', 'Our house is here.'],
        ['their', 'их', 'Their children are here.'],
        ['a neighbour', 'сосед', 'Our neighbours are nice.'],
        ['with', 'с', 'Play with mine.'],
        ['ours', 'наш (без вещи)', 'This house is ours.'],
      ],
      rule: ['Their, there и they are', 'Три слова звучат одинаково, а значат разное: their — их, there — там, they\'re — они есть. На письме их путают даже носители, и это первое, что выдаёт небрежный текст.'],
      quiz: [
        ['«Их дети» —', ['their children', 'there children', "they're children"], 0],
        ['«Это наш дом» —', ['This is our house', 'This is ours house', 'This is us house'], 0],
        ['«Этот дом наш» —', ['This house is ours', 'This house is our', 'This house is us'], 0],
      ],
      order: ['Это наш дом.', 'This is our house.'],
      produce: [
        ['Это их дом.', 'This is their house.', []],
        ['Наши соседи хорошие.', 'Our neighbours are nice.', []],
        ['Этот дом наш.', 'This house is ours.', []],
      ],
    },
    {
      title: 'How many people in your family?',
      summary: 'Размер семьи и кто с кем живёт.',
      topics: [F, Q, HG],
      dialogue: ['Сколько вас', [
        ['Ben', 'How many people are there in your family?', 'Сколько человек у вас в семье?'],
        ['Anna', 'Five: my parents, my two brothers and me.', 'Пятеро: родители, два брата и я.'],
        ['Ben', 'Do you live together?', 'Вы живёте вместе?'],
        ['Anna', 'No, I live alone now.', 'Нет, я сейчас живу одна.'],
        ['Ben', 'Same here.', 'Я тоже.'],
      ]],
      words: [
        ['together', 'вместе', 'We live together.'],
        ['alone', 'один, в одиночестве', 'I live alone.'],
        ['and me', 'и я', 'My brothers and me.'],
        ['Same here.', 'У меня так же.', 'I live alone. — Same here.'],
        ['How many people?', 'Сколько человек?', 'How many people are there?'],
      ],
      rule: ['Alone и lonely', 'Alone — просто один, без оценки: I live alone. Lonely — одиноко, грустно. Сказать I am lonely значит пожаловаться, а I live alone — просто сообщить факт.'],
      quiz: [
        ['«Я живу один» —', ['I live alone', 'I live lonely', 'I am live alone'], 0],
        ['«Сколько человек в вашей семье?» —', ['How many people are there in your family?', 'How much people in your family?', 'How many peoples your family?'], 0],
        ['«У меня так же» —', ['Same here', 'Here same it', 'The same to here'], 0],
      ],
      order: ['Мы живём вместе.', 'We live together.'],
      produce: [
        ['Я сейчас живу одна.', 'I live alone now.', []],
        ['Вы живёте вместе?', 'Do you live together?', []],
        ['У меня так же.', 'Same here.', []],
      ],
    },
    {
      title: 'My friend from school',
      summary: 'Друзья: откуда вы знакомы.',
      topics: [F, PS],
      dialogue: ['Старый друг', [
        ['Anna', 'Who is that?', 'Кто это?'],
        ['Ben', 'My friend from school. We know each other twenty years.', 'Мой школьный друг. Мы знакомы двадцать лет.'],
        ['Anna', 'Do you see him often?', 'Часто видитесь?'],
        ['Ben', 'Not often, he lives in Spain.', 'Не часто, он живёт в Испании.'],
        ['Anna', 'But you keep in touch?', 'Но общаетесь?'],
      ]],
      words: [
        ['from school', 'со школы', 'My friend from school.'],
        ['each other', 'друг друга', 'We know each other.'],
        ['often', 'часто', 'Do you see him often?'],
        ['keep in touch', 'поддерживать связь', 'We keep in touch.'],
        ['a colleague', 'коллега', 'A colleague from work.'],
      ],
      rule: ['Друг откуда — через from', 'Откуда знаком человек, говорят через from: a friend from school, a colleague from work. Предлог всегда from, даже если по-русски мы скажем «школьный друг» одним прилагательным.'],
      quiz: [
        ['«Мой школьный друг» —', ['my friend from school', 'my school of friend', 'my friend of the school'], 0],
        ['«Мы знаем друг друга» —', ['We know each other', 'We know ourselves', 'We know one to other'], 0],
        ['«Часто видитесь?» —', ['Do you see him often?', 'Do you often see him it?', 'Are you see him often?'], 0],
      ],
      order: ['Мы знакомы двадцать лет.', 'We know each other twenty years.'],
      produce: [
        ['Мой школьный друг.', 'My friend from school.', []],
        ['Он живёт в Испании.', 'He lives in Spain.', []],
        ['Мы поддерживаем связь.', 'We keep in touch.', []],
      ],
    },
    {
      title: 'Birthdays and ages',
      summary: 'Когда день рождения и сколько кому лет.',
      topics: [F, 'a1-prepositions-time'],
      dialogue: ['День рождения', [
        ['Ben', 'When is your birthday?', 'Когда у тебя день рождения?'],
        ['Anna', 'In May. And yours?', 'В мае. А у тебя?'],
        ['Ben', 'In two weeks, actually.', 'Вообще-то через две недели.'],
        ['Anna', 'Really? How old are you now?', 'Правда? Сколько тебе сейчас?'],
        ['Ben', 'Thirty-one on Friday.', 'В пятницу тридцать один.'],
      ]],
      words: [
        ['a birthday', 'день рождения', 'When is your birthday?'],
        ['in May', 'в мае', 'My birthday is in May.'],
        ['actually', 'вообще-то', 'In two weeks, actually.'],
        ['Happy birthday!', 'С днём рождения!', 'Happy birthday, Anna!'],
        ['a present', 'подарок', 'A birthday present.'],
      ],
      rule: ['Месяцы идут с in', 'Месяц и год — с in: in May, in 2026. День — с on: on Friday, on the fifth of May. Правило то же, что с частями дня: чем крупнее отрезок, тем «шире» предлог.'],
      quiz: [
        ['«В мае» —', ['in May', 'on May', 'at May'], 0],
        ['«В пятницу» —', ['on Friday', 'in Friday', 'at Friday'], 0],
        ['«С днём рождения!» —', ['Happy birthday!', 'Happy day of birth!', 'Congratulations birthday!'], 0],
      ],
      order: ['Когда у тебя день рождения?', 'When is your birthday?'],
      produce: [
        ['Мой день рождения в мае.', 'My birthday is in May.', []],
        ['С днём рождения!', 'Happy birthday!', []],
        ['Через две недели.', 'In two weeks.', []],
      ],
    },
    {
      title: 'Pets',
      summary: 'Домашние животные — и вечная тема для разговора.',
      topics: [HG, F, D],
      dialogue: ['Собака', [
        ['Anna', 'Have you got a pet?', 'У тебя есть питомец?'],
        ['Ben', 'Yes, a dog. His name is Max.', 'Да, собака. Его зовут Макс.'],
        ['Anna', 'How old is he?', 'Сколько ему?'],
        ['Ben', 'Three. He is very friendly.', 'Три. Он очень дружелюбный.'],
        ['Anna', 'I have got a cat. She is lazy.', 'У меня кошка. Ленивая.'],
      ]],
      words: [
        ['a pet', 'домашний питомец', 'Have you got a pet?'],
        ['a dog', 'собака', 'My dog is friendly.'],
        ['a cat', 'кошка', 'The cat is lazy.'],
        ['friendly', 'дружелюбный', 'He is very friendly.'],
        ['lazy', 'ленивый', 'My cat is lazy.'],
      ],
      rule: ['О животных говорят he и she', 'Формально животное — it, но о своём питомце всегда говорят he или she: his name is Max, she is lazy. Назвать чужую собаку it на прогулке — почти невежливо.'],
      quiz: [
        ['«У тебя есть питомец?» —', ['Have you got a pet?', 'Have you a pet got?', 'Do you have got a pet?'], 0],
        ['«Его зовут Макс» —', ['His name is Max', 'He name is Max', 'His name Max is'], 0],
        ['«Она ленивая» —', ['She is lazy', 'She has lazy', 'She is a lazy'], 0],
      ],
      order: ['У меня есть собака.', 'I have got a dog.'],
      produce: [
        ['У тебя есть питомец?', 'Have you got a pet?', ['Do you have a pet?']],
        ['Его зовут Макс.', 'His name is Max.', []],
        ['Он очень дружелюбный.', 'He is very friendly.', ["He's very friendly."]],
      ],
    },
    {
      title: 'Where are you from, family?',
      summary: 'Откуда родом семья и где живёт сейчас.',
      topics: [F, 'a1-tema-travel', PS],
      dialogue: ['Корни', [
        ['Ben', 'Is your family from {city}?', 'Твоя семья из {город}?'],
        ['Anna', 'My parents are, but I was born in another city.', 'Родители да, а я родилась в другом городе.'],
        ['Ben', 'And now they live in {city}?', 'И сейчас живут в {city}?'],
        ['Anna', 'Yes, near the centre.', 'Да, рядом с центром.'],
        ['Ben', 'Do you visit them often?', 'Часто их навещаешь?'],
      ]],
      words: [
        ['I was born', 'я родился', 'I was born in {city}.'],
        ['visit', 'навещать', 'I visit them often.'],
        ['them', 'их (кого)', 'I visit them.'],
        ['a hometown', 'родной город', 'My hometown is small.'],
        ['move', 'переезжать', 'They move to London.'],
      ],
      rule: ['I was born — единственная форма', 'Про рождение говорят только так: I was born, she was born. Это прошедшее время и страдательный залог сразу, но на A1 его учат целой фразой — разбирать устройство пока незачем.'],
      quiz: [
        ['«Я родился в {город}» —', ['I was born in {city}', 'I am born in {city}', 'I born in {city}'], 0],
        ['«Я часто их навещаю» —', ['I visit them often', 'I visit they often', 'I often visit them it'], 0],
        ['«Мой родной город маленький» —', ['My hometown is small', 'My home town small is', 'My hometown small'], 0],
      ],
      order: ['Я родился в {город}.', 'I was born in {city}.'],
      produce: [
        ['Я родился в {город}.', 'I was born in {city}.', []],
        ['Я часто их навещаю.', 'I visit them often.', []],
        ['Мои родители живут рядом с центром.', 'My parents live near the centre.', []],
      ],
    },
    {
      title: 'Talking about age politely',
      summary: 'О возрасте — осторожно.',
      topics: [F, Q, B],
      dialogue: ['Неудобный вопрос', [
        ['Ben', 'How old is your mother?', 'Сколько лет твоей маме?'],
        ['Anna', 'Oh, that is a secret!', 'О, это секрет!'],
        ['Ben', 'Sorry, my mistake.', 'Извини, моя ошибка.'],
        ['Anna', 'It is fine. She is about sixty.', 'Ничего. Ей около шестидесяти.'],
        ['Ben', 'She looks young.', 'Она выглядит молодо.'],
      ]],
      words: [
        ['a secret', 'секрет', 'That is a secret!'],
        ['She looks young.', 'Она выглядит молодо.', 'She looks young for sixty.'],
        ['in her forties', 'ей за сорок', 'She is in her forties.'],
        ['older', 'старше', 'He is older than me.'],
        ['younger', 'младше', 'She is younger.'],
      ],
      rule: ['О чужом возрасте не спрашивают', 'В Британии и Америке вопрос how old are you взрослому человеку — почти бестактность, особенно женщине. Безопасный обход — сказать о своём возрасте и подождать: если захотят, ответят сами.'],
      quiz: [
        ['«Она выглядит молодо» —', ['She looks young', 'She is looking young at', 'She looks like young'], 0],
        ['«Он старше меня» —', ['He is older than me', 'He is more old than me', 'He is older that me'], 0],
        ['«Ей за сорок» —', ['She is in her forties', 'She is on her forty', 'She has her forties'], 0],
      ],
      order: ['Она выглядит молодо.', 'She looks young.'],
      produce: [
        ['Это секрет!', 'That is a secret!', ["That's a secret!"]],
        ['Он старше меня.', 'He is older than me.', []],
        ['Она младше.', 'She is younger.', ["She's younger."]],
      ],
    },
    {
      title: 'Family and work',
      summary: 'Как совмещают детей и работу — и что об этом говорят.',
      topics: [F, PS, 'a1-tema-work'],
      dialogue: ['С детьми и работой', [
        ['Anna', 'Do you work full time?', 'Ты работаешь полный день?'],
        ['Ben', 'Part time, because of my son.', 'Неполный, из-за сына.'],
        ['Anna', 'Who looks after him?', 'Кто с ним сидит?'],
        ['Ben', 'My mother, twice a week.', 'Моя мама, два раза в неделю.'],
        ['Anna', 'That helps a lot.', 'Это очень помогает.'],
      ]],
      words: [
        ['full time', 'полный день', 'I work full time.'],
        ['part time', 'неполный день', 'She works part time.'],
        ['because of', 'из-за', 'Because of my son.'],
        ['look after', 'присматривать за', 'Who looks after him?'],
        ['help', 'помогать; помощь', 'That helps a lot.'],
      ],
      rule: ['Because и because of', 'Because ведёт целое предложение: because I have a son. Because of — только существительное: because of my son. Смешивать нельзя, а по-русски и то и другое звучит как «из-за».'],
      quiz: [
        ['«Из-за сына» —', ['because of my son', 'because my son', 'for because of son'], 0],
        ['«Кто за ним присматривает?» —', ['Who looks after him?', 'Who look after him?', 'Who looks him after?'], 0],
        ['«Я работаю неполный день» —', ['I work part time', 'I work part of time', 'I am work part time'], 0],
      ],
      order: ['Она работает неполный день.', 'She works part time.'],
      produce: [
        ['Ты работаешь полный день?', 'Do you work full time?', []],
        ['Из-за сына.', 'Because of my son.', []],
        ['Это очень помогает.', 'That helps a lot.', ['It helps a lot.']],
      ],
    },
    {
      title: 'A photo on the phone',
      summary: 'Показать фото и ответить на вопросы о нём.',
      topics: [F, D, 'a1-present-continuous'],
      dialogue: ['Фото с моря', [
        ['Anna', 'Look, this is us in Spain.', 'Смотри, это мы в Испании.'],
        ['Ben', 'Nice photo! Who is this, on the left?', 'Хорошее фото! Кто это слева?'],
        ['Anna', 'My sister. She is holding my daughter.', 'Моя сестра. Она держит мою дочь.'],
        ['Ben', 'They look happy.', 'Они выглядят счастливыми.'],
        ['Anna', 'It was a good week.', 'Была хорошая неделя.'],
      ]],
      words: [
        ['a photo', 'фотография', 'A nice photo.'],
        ['hold', 'держать', 'She is holding my daughter.'],
        ['happy', 'счастливый', 'They look happy.'],
        ['us', 'нас', 'This is us in Spain.'],
        ['It was', 'это было', 'It was a good week.'],
      ],
      rule: ['Описание фотографии — длительное время', 'На фотографии всё происходит: she is holding, they are smiling, we are standing. Поэтому фото описывают в present continuous, хотя снимок и сделан давно. Так же говорят о картинах и о том, что видно в окне.'],
      quiz: [
        ['«Она держит мою дочь» —', ['She is holding my daughter', 'She holds my daughter now is', 'She is hold my daughter'], 0],
        ['«Они выглядят счастливыми» —', ['They look happy', 'They are look happy', 'They looks happy'], 0],
        ['«Это мы в Испании» —', ['This is us in Spain', 'This is we in Spain', 'These is us in Spain'], 0],
      ],
      order: ['Это мы в Испании.', 'This is us in Spain.'],
      produce: [
        ['Хорошее фото!', 'Nice photo!', []],
        ['Они выглядят счастливыми.', 'They look happy.', []],
        ['Она держит мою дочь.', 'She is holding my daughter.', ["She's holding my daughter."]],
      ],
    },
    {
      title: 'Telling about your family',
      summary: 'Собрать рассказ о семье в пять предложений.',
      topics: [F, HG, PS],
      dialogue: ['Рассказ целиком', [
        ['Anna', 'I have got a big family: parents, two brothers and a daughter.', 'У меня большая семья: родители, два брата и дочь.'],
        ['Ben', 'Do they live near?', 'Они живут рядом?'],
        ['Anna', 'My parents do. My brothers live in another city.', 'Родители да. Братья в другом городе.'],
        ['Ben', 'And your daughter?', 'А дочь?'],
        ['Anna', 'She is seven and she goes to school.', 'Ей семь, она ходит в школу.'],
      ]],
      words: [
        ['another', 'другой', 'Another city.'],
        ['goes to school', 'ходит в школу', 'She goes to school.'],
        ['My parents do.', 'Родители да.', 'Do they live near? — My parents do.'],
        ['a grandfather', 'дедушка', 'My grandfather is ninety.'],
        ['close', 'близкий', 'We are a close family.'],
      ],
      rule: ['Ответ через do вместо повтора', 'Чтобы не повторять глагол, англичане отвечают вспомогательным: do they live near — my parents do. Так же с to be: is she a teacher — yes, she is. Это делает речь короче и звучит естественно.'],
      quiz: [
        ['«Родители — да» (в ответ на do they live near) —', ['My parents do', 'My parents live', 'My parents are'], 0],
        ['«Она ходит в школу» —', ['She goes to school', 'She go to school', 'She goes to the school every'], 0],
        ['«В другом городе» —', ['in another city', 'in other city', 'in an another city'], 0],
      ],
      order: ['Она ходит в школу.', 'She goes to school.'],
      produce: [
        ['У меня большая семья.', 'I have got a big family.', ['I have a big family.']],
        ['Братья живут в другом городе.', 'My brothers live in another city.', []],
        ['Мы близкая семья.', 'We are a close family.', ["We're a close family."]],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: семья',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [HG, F, D, PS],
      produce: [
        ['У меня есть сестра.', 'I have got a sister.', ['I have a sister.']],
        ['У него голубые глаза.', 'He has got blue eyes.', []],
        ['Какая твоя сестра?', 'What is your sister like?', ["What's your sister like?"]],
        ['Он работает в банке.', 'He works in a bank.', []],
        ['Мой день рождения в мае.', 'My birthday is in May.', []],
        ['У тебя есть питомец?', 'Have you got a pet?', ['Do you have a pet?']],
      ],
    },
  ],
}
