// Блок 10 — Home. Описать жильё и сказать, где что стоит.
//
// Грамматика — there is / there are. Она нужна раньше, чем кажется: без неё не
// объяснить, что в номере нет полотенца, а в квартире есть балкон. Здесь же вся бытовая
// лексика, которой не хватает при переезде.

const H = 'a1-tema-home'
const D = 'a1-tema-description'
const B = 'a1-to-be'
const Q = 'a1-questions'
const PL = 'a1-plural'
const HG = 'a1-have-got'
const PR = 'a1-prepositions-time'

export default {
  slug: 'home',
  title: 'Home',
  subtitle: 'there is / there are: описать квартиру и сказать, где что стоит',
  canDo: [
    'сказать, что есть и чего нет в квартире',
    'назвать комнаты и мебель',
    'описать, где стоит вещь',
    'спросить об аренде и коммунальных',
    'объяснить, что сломалось дома',
  ],
  lessons: [
    {
      title: 'There is a kitchen',
      summary: 'Сказать, что в квартире есть.',
      topics: [H, D],
      dialogue: ['Смотрим квартиру', [
        ['Агент', 'There is a kitchen and one bedroom.', 'Здесь кухня и одна спальня.'],
        ['Anna', 'Is there a balcony?', 'Балкон есть?'],
        ['Агент', 'Yes, there is. A small one.', 'Да, есть. Маленький.'],
        ['Anna', 'And a lift?', 'А лифт?'],
        ['Агент', 'No, there is not. Third floor.', 'Нет. Третий этаж.'],
      ]],
      words: [
        ['a kitchen', 'кухня', 'The kitchen is small.'],
        ['a bedroom', 'спальня', 'One bedroom, please.'],
        ['a balcony', 'балкон', 'There is a balcony.'],
        ['a lift', 'лифт', 'There is no lift.'],
        ['There is not.', 'Нет (не имеется).', 'A lift? No, there is not.'],
      ],
      rule: ['There is для одного, there are для многих', 'There is a kitchen, there are two bedrooms. В отрицании обычно говорят there is no lift — короче и естественнее, чем there is not a lift. Это самая частая фраза при осмотре жилья.'],
      quiz: [
        ['«Есть балкон?» —', ['Is there a balcony?', 'Is it a balcony?', 'Have there a balcony?'], 0],
        ['«Две спальни» —', ['There are two bedrooms', 'There is two bedrooms', 'There are two bedroom'], 0],
        ['«Лифта нет» —', ['There is no lift', 'There is not lift a', 'It has no lift there'], 0],
      ],
      order: ['Здесь кухня и одна спальня.', 'There is a kitchen and one bedroom.'],
      produce: [
        ['Балкон есть?', 'Is there a balcony?', []],
        ['Лифта нет.', 'There is no lift.', []],
        ['Кухня маленькая.', 'The kitchen is small.', []],
      ],
    },
    {
      title: 'Rooms',
      summary: 'Названия комнат и что в них происходит.',
      topics: [H, PL],
      dialogue: ['Экскурсия по дому', [
        ['Ben', 'This is the living room.', 'Это гостиная.'],
        ['Anna', 'And the bathroom?', 'А ванная?'],
        ['Ben', 'Next to the bedroom, on the left.', 'Рядом со спальней, слева.'],
        ['Anna', 'Nice and light.', 'Светло и приятно.'],
        ['Ben', 'The kitchen is small, but that is fine.', 'Кухня маленькая, но это нормально.'],
      ]],
      words: [
        ['a living room', 'гостиная', 'The living room is big.'],
        ['a bathroom', 'ванная', 'The bathroom is here.'],
        ['a hall', 'прихожая', 'Leave it in the hall.'],
        ['a floor', 'пол; этаж', 'The floor is cold.'],
        ['a wall', 'стена', 'A picture on the wall.'],
      ],
      rule: ['Bathroom и toilet', 'В Британии bathroom — комната с ванной, а туалет отдельно и называется toilet или loo. В Америке bathroom значит и туалет тоже, поэтому вопрос where is the bathroom понимают везде и он самый безопасный.'],
      quiz: [
        ['«Гостиная» —', ['a living room', 'a live room', 'a room living'], 0],
        ['«На стене» —', ['on the wall', 'in the wall', 'at wall'], 0],
        ['Самый безопасный вопрос о туалете:', ['Where is the bathroom?', 'Where is the loo place?', 'Where toilet is?'], 0],
      ],
      order: ['Ванная рядом со спальней.', 'The bathroom is next to the bedroom.'],
      produce: [
        ['Это гостиная.', 'This is the living room.', []],
        ['Картина на стене.', 'A picture on the wall.', []],
        ['Пол холодный.', 'The floor is cold.', []],
      ],
    },
    {
      title: 'Furniture',
      summary: 'Мебель и техника.',
      topics: [H, D, PL],
      dialogue: ['Что уже есть', [
        ['Anna', 'Is there a fridge?', 'Холодильник есть?'],
        ['Агент', 'Yes, and a washing machine.', 'Да, и стиральная машина.'],
        ['Anna', 'A table and chairs?', 'Стол и стулья?'],
        ['Агент', 'A table, four chairs, a sofa.', 'Стол, четыре стула, диван.'],
        ['Anna', 'Good, I have nothing.', 'Хорошо, у меня ничего нет.'],
      ]],
      words: [
        ['a fridge', 'холодильник', 'The fridge is empty.'],
        ['a washing machine', 'стиральная машина', 'Is there a washing machine?'],
        ['a sofa', 'диван', 'A sofa in the living room.'],
        ['a cooker', 'плита', 'The cooker is new.'],
        ['nothing', 'ничего', 'I have nothing.'],
      ],
      rule: ['Furniture нельзя посчитать', 'Furniture — «мебель» вообще, и множественного числа у него нет: much furniture, a lot of furniture, но не two furnitures. Считают предметы: two chairs, a table.'],
      quiz: [
        ['«Мебель» во множественном —', ['furniture', 'furnitures', 'a furnitures'], 0],
        ['«Стиральная машина» —', ['a washing machine', 'a wash machine', 'a machine of washing'], 0],
        ['«У меня ничего нет» —', ['I have nothing', 'I have not nothing', 'I do not have nothing'], 0],
      ],
      order: ['Стол, четыре стула, диван.', 'A table, four chairs, a sofa.'],
      produce: [
        ['Холодильник есть?', 'Is there a fridge?', []],
        ['Диван в гостиной.', 'A sofa in the living room.', []],
        ['Плита новая.', 'The cooker is new.', []],
      ],
    },
    {
      title: 'Where is it exactly?',
      summary: 'Точное место: на, в, за, между.',
      topics: [H, D, Q],
      dialogue: ['Поиски пульта', [
        ['Ben', 'Where is the remote?', 'Где пульт?'],
        ['Anna', 'Behind the sofa, maybe.', 'Может, за диваном.'],
        ['Ben', 'No. Between the books?', 'Нет. Между книгами?'],
        ['Anna', 'Look in front of the TV.', 'Посмотри перед телевизором.'],
        ['Ben', 'Found it. Thank you.', 'Нашёл. Спасибо.'],
      ]],
      words: [
        ['behind', 'за, позади', 'Behind the sofa.'],
        ['between', 'между', 'Between the books.'],
        ['in front of', 'перед', 'In front of the TV.'],
        ['a TV', 'телевизор', 'The TV is on.'],
        ['a remote', 'пульт', 'Where is the remote?'],
      ],
      rule: ['In front of и before', 'В пространстве — in front of the TV. Во времени — before six. Русское «перед» покрывает оба случая, английское делит их между двумя разными выражениями, и подмена звучит странно.'],
      quiz: [
        ['«За диваном» —', ['behind the sofa', 'after the sofa', 'behind of the sofa'], 0],
        ['«Перед телевизором» —', ['in front of the TV', 'before the TV', 'in the front TV'], 0],
        ['«Между книгами» —', ['between the books', 'among the book', 'between of books'], 0],
      ],
      order: ['Пульт за диваном.', 'The remote is behind the sofa.'],
      produce: [
        ['Где пульт?', 'Where is the remote?', []],
        ['Перед телевизором.', 'In front of the TV.', []],
        ['Между книгами.', 'Between the books.', []],
      ],
    },
    {
      title: 'How much is the rent?',
      summary: 'Аренда, залог и коммунальные.',
      topics: [H, 'a1-tema-shopping', Q],
      dialogue: ['Условия', [
        ['Anna', 'How much is the rent?', 'Сколько стоит аренда?'],
        ['Агент', 'Eight hundred a month.', 'Восемьсот в месяц.'],
        ['Anna', 'Are bills included?', 'Коммунальные включены?'],
        ['Агент', 'Water is, electricity is not.', 'Вода да, электричество нет.'],
        ['Anna', 'And the deposit?', 'А залог?'],
      ]],
      words: [
        ['rent', 'аренда', 'The rent is high.'],
        ['a month', 'месяц', 'Eight hundred a month.'],
        ['bills', 'коммунальные счета', 'Are bills included?'],
        ['included', 'включено', 'Water is included.'],
        ['a deposit', 'залог', 'One month deposit.'],
      ],
      rule: ['A month — «в месяц»', 'Периодичность цены даётся через a: eight hundred a month, twenty a day, fifty an hour. Предлог per тоже верен, но звучит официально, как в договоре, а не в разговоре.'],
      quiz: [
        ['«Восемьсот в месяц» —', ['eight hundred a month', 'eight hundred in month', 'eight hundred of month'], 0],
        ['«Коммунальные включены?» —', ['Are bills included?', 'Is bills included?', 'Are the bills include?'], 0],
        ['«Залог» —', ['a deposit', 'a pledge money', 'a rent back'], 0],
      ],
      order: ['Сколько стоит аренда?', 'How much is the rent?'],
      produce: [
        ['Восемьсот в месяц.', 'Eight hundred a month.', []],
        ['Коммунальные включены?', 'Are bills included?', []],
        ['Вода включена.', 'Water is included.', []],
      ],
    },
    {
      title: 'My flat is on the fourth floor',
      summary: 'Рассказать, где живёшь.',
      topics: [H, D, B],
      dialogue: ['Про свой дом', [
        ['Ben', 'Where do you live exactly?', 'Где именно ты живёшь?'],
        ['Anna', 'In {city}, near the park.', 'В {город}, рядом с парком.'],
        ['Ben', 'A house or a flat?', 'Дом или квартира?'],
        ['Anna', 'A flat, on the fourth floor.', 'Квартира, на четвёртом этаже.'],
        ['Ben', 'With a lift, I hope!', 'Надеюсь, с лифтом!'],
      ]],
      words: [
        ['exactly', 'точно, именно', 'Where exactly?'],
        ['on the fourth floor', 'на четвёртом этаже', 'I live on the fourth floor.'],
        ['a neighbour', 'сосед', 'My neighbour is quiet.'],
        ['upstairs', 'наверху', 'The neighbours upstairs.'],
        ['I hope', 'надеюсь', 'With a lift, I hope.'],
      ],
      rule: ['On the floor и on the fourth floor', 'Этаж всегда с on: on the fourth floor. Но on the floor без числа значит «на полу». Разница только в артикле с числительным, и в разговоре это слышно сразу.'],
      quiz: [
        ['«На четвёртом этаже» —', ['on the fourth floor', 'in the fourth floor', 'at fourth floor'], 0],
        ['«Соседи наверху» —', ['the neighbours upstairs', 'the upstairs of neighbours', 'the neighbours on up'], 0],
        ['«Где именно ты живёшь?» —', ['Where do you live exactly?', 'Where exactly you live?', 'Where do you exactly living?'], 0],
      ],
      order: ['Я живу на четвёртом этаже.', 'I live on the fourth floor.'],
      produce: [
        ['Я живу в {город}, рядом с парком.', 'I live in {city}, near the park.', []],
        ['Квартира на четвёртом этаже.', 'A flat on the fourth floor.', []],
        ['Мой сосед тихий.', 'My neighbour is quiet.', []],
      ],
    },
    {
      title: 'The tap is broken',
      summary: 'Что сломалось и кому звонить.',
      topics: [H, 'a1-tema-problems'],
      dialogue: ['Вызов мастера', [
        ['Anna', 'The tap is broken.', 'Кран сломан.'],
        ['Хозяин', 'Since when?', 'С каких пор?'],
        ['Anna', 'Since yesterday. Water everywhere.', 'Со вчера. Вода везде.'],
        ['Хозяин', 'I send a plumber tomorrow.', 'Завтра пришлю сантехника.'],
        ['Anna', 'Thank you, that is quick.', 'Спасибо, это быстро.'],
      ]],
      words: [
        ['a tap', 'кран', 'The tap is broken.'],
        ['a plumber', 'сантехник', 'I need a plumber.'],
        ['everywhere', 'везде', 'Water everywhere.'],
        ['since yesterday', 'со вчерашнего дня', 'It is broken since yesterday.'],
        ['send', 'посылать', 'I send a plumber.'],
      ],
      rule: ['Broken — уже сломан', 'Broken описывает состояние: the tap is broken, the phone is broken. Это причастие, и оно ведёт себя как прилагательное — с to be, а не с have. Русское «сломался» переводится именно так.'],
      quiz: [
        ['«Кран сломан» —', ['The tap is broken', 'The tap has broken it', 'The tap is break'], 0],
        ['«Мне нужен сантехник» —', ['I need a plumber', 'I need plumber', 'I am need a plumber'], 0],
        ['«Вода везде» —', ['Water everywhere', 'Water in everywhere', 'The water every where'], 0],
      ],
      order: ['Мне нужен сантехник.', 'I need a plumber.'],
      produce: [
        ['Кран сломан.', 'The tap is broken.', []],
        ['Мне нужен сантехник.', 'I need a plumber.', []],
        ['Вода везде.', 'Water everywhere.', []],
      ],
    },
    {
      title: 'It is cold in here',
      summary: 'Отопление, окна и температура дома.',
      topics: [H, B, 'a1-tema-weather'],
      dialogue: ['Холодно', [
        ['Ben', 'It is cold in here.', 'Здесь холодно.'],
        ['Anna', 'The heating is off.', 'Отопление выключено.'],
        ['Ben', 'Can we turn it on?', 'Можем включить?'],
        ['Anna', 'Yes, the button is in the hall.', 'Да, кнопка в прихожей.'],
        ['Ben', 'Much better now.', 'Уже лучше.'],
      ]],
      words: [
        ['heating', 'отопление', 'The heating is off.'],
        ['turn on', 'включить', 'Can we turn it on?'],
        ['turn off', 'выключить', 'Turn off the light.'],
        ['a button', 'кнопка', 'The button is here.'],
        ['much better', 'намного лучше', 'Much better now.'],
      ],
      rule: ['Turn it on, а не turn on it', 'Если предмет назван местоимением, он встаёт внутрь: turn it on, turn them off. С обычным словом можно и так и так: turn on the light, turn the light on. Ошибка turn on it слышна сразу.'],
      quiz: [
        ['«Включи его» —', ['turn it on', 'turn on it', 'on turn it'], 0],
        ['«Выключи свет» —', ['turn off the light', 'turn the off light', 'off turn the light'], 0],
        ['«Здесь холодно» —', ['It is cold in here', 'Here is cold it', 'In here cold is'], 0],
      ],
      order: ['Можем включить отопление?', 'Can we turn on the heating?'],
      produce: [
        ['Здесь холодно.', 'It is cold in here.', ["It's cold in here."]],
        ['Отопление выключено.', 'The heating is off.', []],
        ['Выключи свет.', 'Turn off the light.', []],
      ],
    },
    {
      title: 'Neighbours and noise',
      summary: 'Шум, тишина и вежливая просьба.',
      topics: [H, 'a1-tema-problems', 'a1-can'],
      dialogue: ['Ночью', [
        ['Anna', 'Sorry, it is very late.', 'Извините, уже очень поздно.'],
        ['Сосед', 'Oh, is the music loud?', 'Ой, музыка громкая?'],
        ['Anna', 'A little. Can you turn it down?', 'Немного. Можете сделать потише?'],
        ['Сосед', 'Of course, sorry!', 'Конечно, извините!'],
        ['Anna', 'Thank you, good night.', 'Спасибо, спокойной ночи.'],
      ]],
      words: [
        ['loud', 'громкий', 'The music is loud.'],
        ['turn down', 'сделать тише', 'Can you turn it down?'],
        ['noise', 'шум', 'The noise is bad at night.'],
        ['Good night.', 'Спокойной ночи.', 'Thank you, good night.'],
        ['a little', 'немного', 'A little loud.'],
      ],
      rule: ['Как просят соседа', 'Формула вежливой просьбы: извинение → мягкая констатация → просьба через can you. Прямое turn it down без обрамления звучит как приказ, и именно на этом ссорятся с соседями чаще всего.'],
      quiz: [
        ['«Можете сделать потише?» —', ['Can you turn it down?', 'Can you turn down it?', 'Can you it turn down?'], 0],
        ['«Музыка громкая» —', ['The music is loud', 'The music is loudly', 'The loud is music'], 0],
        ['«Спокойной ночи» —', ['Good night', 'Good evening night', 'Night good'], 0],
      ],
      order: ['Можете сделать потише?', 'Can you turn it down?'],
      produce: [
        ['Музыка громкая.', 'The music is loud.', []],
        ['Можете сделать потише?', 'Can you turn it down?', []],
        ['Спасибо, спокойной ночи.', 'Thank you, good night.', []],
      ],
    },
    {
      title: 'Cleaning day',
      summary: 'Уборка и домашние дела.',
      topics: [H, 'a1-present-simple'],
      dialogue: ['Суббота', [
        ['Ben', 'I clean the flat on Saturday.', 'Я убираю квартиру по субботам.'],
        ['Anna', 'All day?', 'Весь день?'],
        ['Ben', 'Two hours. I wash the floor and the dishes.', 'Два часа. Мою пол и посуду.'],
        ['Anna', 'And the windows?', 'А окна?'],
        ['Ben', 'Twice a year, honestly.', 'Дважды в год, если честно.'],
      ]],
      words: [
        ['clean', 'убирать; чистый', 'I clean the flat.'],
        ['wash', 'мыть', 'I wash the dishes.'],
        ['dishes', 'посуда', 'Wash the dishes, please.'],
        ['tidy', 'прибранный', 'The room is tidy.'],
        ['a mess', 'беспорядок', 'What a mess!'],
      ],
      rule: ['Wash и clean', 'Wash — мыть водой: wash the dishes, wash your hands. Clean — убирать вообще: clean the room, clean the table. Помыть комнату по-английски нельзя, а убрать посуду — можно, но это уже про «унести».'],
      quiz: [
        ['«Мою посуду» —', ['I wash the dishes', 'I clean the dishes water', 'I wash dishes the'], 0],
        ['«Комната прибрана» —', ['The room is tidy', 'The room is tidied up it', 'The tidy is room'], 0],
        ['«Какой беспорядок!» —', ['What a mess!', 'What mess!', 'Which a mess is!'], 0],
      ],
      order: ['Я убираю квартиру по субботам.', 'I clean the flat on Saturday.'],
      produce: [
        ['Я мою посуду.', 'I wash the dishes.', []],
        ['Комната прибрана.', 'The room is tidy.', []],
        ['Какой беспорядок!', 'What a mess!', []],
      ],
    },
    {
      title: 'Moving in',
      summary: 'Переезд: коробки, ключи, первый день.',
      topics: [H, 'a1-present-continuous'],
      dialogue: ['День переезда', [
        ['Anna', 'We are moving in today.', 'Мы сегодня заезжаем.'],
        ['Ben', 'How many boxes?', 'Сколько коробок?'],
        ['Anna', 'Fifteen. And a sofa.', 'Пятнадцать. И диван.'],
        ['Ben', 'I am coming to help.', 'Я приеду помочь.'],
        ['Anna', 'You are a good friend!', 'Ты хороший друг!'],
      ]],
      words: [
        ['move in', 'въезжать', 'We are moving in today.'],
        ['a box', 'коробка', 'Fifteen boxes.'],
        ['heavy', 'тяжёлый', 'The box is heavy.'],
        ['help', 'помогать', 'I am coming to help.'],
        ['a key', 'ключ', 'Here is the key.'],
      ],
      rule: ['Move in и move out', 'Move in — въехать, move out — съехать. Просто move — переехать вообще: we move to London. Предлог здесь несёт весь смысл, и без него фраза остаётся незаконченной.'],
      quiz: [
        ['«Мы сегодня въезжаем» —', ['We are moving in today', 'We move in today are', 'We are move in today'], 0],
        ['«Пятнадцать коробок» —', ['fifteen boxes', 'fifteen box', 'fifteen boxs'], 0],
        ['«Я приеду помочь» —', ['I am coming to help', 'I am coming for help me', 'I come to help am'], 0],
      ],
      order: ['Мы сегодня заезжаем.', 'We are moving in today.'],
      produce: [
        ['Коробка тяжёлая.', 'The box is heavy.', []],
        ['Я приеду помочь.', 'I am coming to help.', ["I'm coming to help."]],
        ['Вот ключ.', 'Here is the key.', []],
      ],
    },
    {
      title: 'What is in the fridge?',
      summary: 'Что есть дома и что купить.',
      topics: [H, 'a1-tema-food', Q],
      dialogue: ['Перед магазином', [
        ['Ben', 'What is in the fridge?', 'Что в холодильнике?'],
        ['Anna', 'Milk, eggs, some cheese.', 'Молоко, яйца, немного сыра.'],
        ['Ben', 'Is there any bread?', 'Хлеб есть?'],
        ['Anna', 'No, there is not any.', 'Нет, нету.'],
        ['Ben', 'Then I buy bread and fruit.', 'Тогда куплю хлеб и фрукты.'],
      ]],
      words: [
        ['cheese', 'сыр', 'Some cheese, please.'],
        ['any', 'какой-нибудь (в вопросе)', 'Is there any bread?'],
        ['buy', 'покупать', 'I buy bread.'],
        ['fruit', 'фрукты', 'Fruit and vegetables.'],
        ['a shopping list', 'список покупок', 'A shopping list on the fridge.'],
      ],
      rule: ['Some и any', 'Some — в утверждении: there is some cheese. Any — в вопросе и отрицании: is there any bread, there is not any bread. Исключение — вежливая просьба: would you like some tea, потому что ответа ждут положительного.'],
      quiz: [
        ['«Хлеб есть?» —', ['Is there any bread?', 'Is there some bread?', 'Is there a bread?'], 0],
        ['«Немного сыра» —', ['some cheese', 'any cheese', 'a cheese'], 0],
        ['«Хлеба нет» —', ['There is not any bread', 'There is not some bread', 'There is no any bread'], 0],
      ],
      order: ['Что в холодильнике?', 'What is in the fridge?'],
      produce: [
        ['Хлеб есть?', 'Is there any bread?', []],
        ['Немного сыра, пожалуйста.', 'Some cheese, please.', []],
        ['Тогда куплю хлеб.', 'Then I buy bread.', []],
      ],
    },
    {
      title: 'A place of my own',
      summary: 'Своё жильё против съёмного.',
      topics: [H, HG, D],
      dialogue: ['Своё или съёмное', [
        ['Ben', 'Do you rent or is it yours?', 'Ты снимаешь или своё?'],
        ['Anna', 'I rent. But I want my own flat.', 'Снимаю. Но хочу свою квартиру.'],
        ['Ben', 'One day.', 'Когда-нибудь.'],
        ['Anna', 'Yes, one day. Rent is expensive here.', 'Да, когда-нибудь. Аренда тут дорогая.'],
        ['Ben', 'Everywhere, honestly.', 'Да везде, честно говоря.'],
      ]],
      words: [
        ['rent', 'снимать (жильё)', 'I rent a flat.'],
        ['my own', 'мой собственный', 'My own flat.'],
        ['one day', 'когда-нибудь', 'One day, yes.'],
        ['want', 'хотеть', 'I want my own flat.'],
        ['honestly', 'честно говоря', 'Everywhere, honestly.'],
      ],
      rule: ['Own только с притяжательным', 'Own не бывает сам по себе: my own flat, her own room. Сказать an own flat нельзя. Зато own усиливает: my flat — просто моя, my own flat — именно своя, не съёмная.'],
      quiz: [
        ['«Своя квартира» —', ['my own flat', 'an own flat', 'the own my flat'], 0],
        ['«Я снимаю квартиру» —', ['I rent a flat', 'I rent flat', 'I am rent a flat'], 0],
        ['«Когда-нибудь» —', ['one day', 'in one day', 'someday one'], 0],
      ],
      order: ['Я хочу свою квартиру.', 'I want my own flat.'],
      produce: [
        ['Я снимаю квартиру.', 'I rent a flat.', []],
        ['Я хочу свою квартиру.', 'I want my own flat.', []],
        ['Аренда тут дорогая.', 'Rent is expensive here.', []],
      ],
    },
    {
      title: 'Guests are coming',
      summary: 'Подготовка к гостям.',
      topics: [H, 'a1-tema-meetings', 'a1-present-continuous'],
      dialogue: ['Перед приходом гостей', [
        ['Anna', 'Guests are coming at seven.', 'Гости придут в семь.'],
        ['Ben', 'What can I do?', 'Что я могу сделать?'],
        ['Anna', 'Clean the table, please.', 'Убери со стола, пожалуйста.'],
        ['Ben', 'And chairs? We have four.', 'А стулья? У нас четыре.'],
        ['Anna', 'Take two from the bedroom.', 'Возьми два из спальни.'],
      ]],
      words: [
        ['a guest', 'гость', 'Guests are coming.'],
        ['What can I do?', 'Что я могу сделать?', 'What can I do to help?'],
        ['take from', 'взять из', 'Take two from the bedroom.'],
        ['ready', 'готовый', 'Everything is ready.'],
        ['put', 'положить, поставить', 'Put it on the table.'],
      ],
      rule: ['Просьба в повелительном — это нормально', 'Clean the table, take two chairs, put it here — по-русски это звучит резко, по-английски с please совершенно обычно. Смягчает не форма глагола, а please и тон.'],
      quiz: [
        ['«Убери со стола, пожалуйста» —', ['Clean the table, please', 'Please you clean the table it', 'Clean please the table you'], 0],
        ['«Возьми два из спальни» —', ['Take two from the bedroom', 'Take two of the bedroom', 'Take from bedroom two'], 0],
        ['«Всё готово» —', ['Everything is ready', 'All are ready it', 'Everything are ready'], 0],
      ],
      order: ['Гости придут в семь.', 'Guests are coming at seven.'],
      produce: [
        ['Что я могу сделать?', 'What can I do?', []],
        ['Поставь это на стол.', 'Put it on the table.', []],
        ['Всё готово.', 'Everything is ready.', []],
      ],
    },
    {
      title: 'My favourite place at home',
      summary: 'Любимое место в доме и почему.',
      topics: [H, D, 'a1-tema-leisure'],
      dialogue: ['Любимый угол', [
        ['Ben', 'What is your favourite place at home?', 'Какое твоё любимое место дома?'],
        ['Anna', 'The chair near the window.', 'Кресло у окна.'],
        ['Ben', 'Why?', 'Почему?'],
        ['Anna', 'It is quiet and there is light.', 'Тихо, и есть свет.'],
        ['Ben', 'Mine is the kitchen.', 'А у меня кухня.'],
      ]],
      words: [
        ['favourite', 'любимый', 'My favourite place.'],
        ['a place', 'место', 'A quiet place.'],
        ['light', 'свет; светлый', 'There is light.'],
        ['Why?', 'Почему?', 'Why the kitchen?'],
        ['because', 'потому что', 'Because it is quiet.'],
      ],
      rule: ['Ответ на why начинается с because', 'На вопрос why отвечают целым предложением с because: because it is quiet. Просто «тихо» по-английски звучит оборванно, а because — обязательная связка, без неё ответ не читается как ответ.'],
      quiz: [
        ['«Потому что тихо» —', ['Because it is quiet', 'Because quiet', 'Because is quiet it'], 0],
        ['«Моё любимое место» —', ['my favourite place', 'my favourite of place', 'the my favourite place'], 0],
        ['«А у меня кухня» —', ['Mine is the kitchen', 'My is the kitchen', 'Mine the kitchen is'], 0],
      ],
      order: ['Потому что там тихо.', 'Because it is quiet.'],
      produce: [
        ['Какое твоё любимое место дома?', 'What is your favourite place at home?', []],
        ['Кресло у окна.', 'The chair near the window.', []],
        ['Потому что там тихо.', 'Because it is quiet.', []],
      ],
    },
    {
      title: 'Describing home in five lines',
      summary: 'Весь блок: рассказать о жилье коротко и понятно.',
      topics: [H, D, PL],
      dialogue: ['Рассказ о доме', [
        ['Anna', 'I live in a flat on the fourth floor.', 'Я живу в квартире на четвёртом этаже.'],
        ['Ben', 'How many rooms?', 'Сколько комнат?'],
        ['Anna', 'Two: a bedroom and a living room.', 'Две: спальня и гостиная.'],
        ['Ben', 'Is there a balcony?', 'Балкон есть?'],
        ['Anna', 'Yes, small but sunny.', 'Да, маленький, но солнечный.'],
      ]],
      words: [
        ['sunny', 'солнечный', 'A sunny room.'],
        ['a room', 'комната', 'How many rooms?'],
        ['comfortable', 'удобный', 'A comfortable sofa.'],
        ['old but nice', 'старый, но приятный', 'The house is old but nice.'],
        ['I like it here.', 'Мне здесь нравится.', 'It is small, but I like it here.'],
      ],
      rule: ['Порядок рассказа о жилье', 'Где → что за жильё → сколько комнат → что есть особенного → как тебе там. Пять шагов, и рассказ закончен. Тот же порядок работает и на собеседовании при аренде, и в разговоре с новым знакомым.'],
      quiz: [
        ['«Маленький, но солнечный» —', ['small but sunny', 'small and but sunny', 'but small sunny'], 0],
        ['«Удобный диван» —', ['a comfortable sofa', 'a sofa comfortable', 'the comfortable of sofa'], 0],
        ['«Мне здесь нравится» —', ['I like it here', 'I like here it', 'I am like it here'], 0],
      ],
      order: ['Я живу в квартире на четвёртом этаже.', 'I live in a flat on the fourth floor.'],
      produce: [
        ['Сколько комнат?', 'How many rooms?', []],
        ['Две: спальня и гостиная.', 'Two: a bedroom and a living room.', []],
        ['Мне здесь нравится.', 'I like it here.', []],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: дом',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [H, D, PL, Q],
      produce: [
        ['Балкон есть?', 'Is there a balcony?', []],
        ['Лифта нет.', 'There is no lift.', []],
        ['Пульт за диваном.', 'The remote is behind the sofa.', []],
        ['Сколько стоит аренда?', 'How much is the rent?', []],
        ['Кран сломан.', 'The tap is broken.', []],
        ['Можете сделать потише?', 'Can you turn it down?', []],
      ],
    },
  ],
}
