// Блок 14 — Weather. Сказать, какая погода, и что будет завтра.
//
// Погода — не про метеорологию, а про то, чем начинают разговор в англоязычной стране.
// Здесь же первое будущее время: going to. Оно приходит именно тут, потому что прогноз
// и планы на выходные — единственное, ради чего новичку правда нужно будущее.

const W = 'a1-tema-weather'
const B = 'a1-to-be'
const D = 'a1-tema-description'
const L = 'a1-tema-leisure'
const Q = 'a1-questions'
const T = 'a1-tema-travel'
const G = 'a1-tema-greetings'

export default {
  slug: 'weather',
  title: 'Weather',
  subtitle: 'Погода, времена года и первое будущее время',
  canDo: [
    'сказать, какая сейчас погода',
    'спросить прогноз на завтра',
    'назвать времена года и месяцы',
    'начать разговор с погоды',
    'сказать, что собираешься делать',
  ],
  lessons: [
    {
      title: 'It is sunny today',
      summary: 'Погода начинается с it.',
      topics: [W, B],
      dialogue: ['У окна', [
        ['Anna', 'It is sunny today!', 'Сегодня солнечно!'],
        ['Ben', 'Yes, and warm.', 'Да, и тепло.'],
        ['Anna', 'Yesterday it was cold.', 'Вчера было холодно.'],
        ['Ben', 'British weather.', 'Британская погода.'],
        ['Anna', 'Let us go outside.', 'Пойдём на улицу.'],
      ]],
      words: [
        ['sunny', 'солнечно', 'It is sunny today.'],
        ['warm', 'тепло', 'It is warm outside.'],
        ['cloudy', 'облачно', 'It is cloudy.'],
        ['windy', 'ветрено', 'It is very windy.'],
        ['It was cold.', 'Было холодно.', 'Yesterday it was cold.'],
      ],
      rule: ['Погода всегда начинается с it', 'It is sunny, it is cold, it is raining. Подлежащего по смыслу нет, но английскому предложению оно нужно, поэтому ставят пустое it. Фраза без него — is sunny today — звучит как обрывок.'],
      quiz: [
        ['«Сегодня солнечно» —', ['It is sunny today', 'Today is sunny it', 'Is sunny today'], 0],
        ['«Очень ветрено» —', ['It is very windy', 'It is very wind', 'There is very windy'], 0],
        ['«Вчера было холодно» —', ['Yesterday it was cold', 'Yesterday it is cold', 'Yesterday was it cold'], 0],
      ],
      order: ['Сегодня солнечно и тепло.', 'It is sunny and warm today.'],
      produce: [
        ['Сегодня солнечно.', 'It is sunny today.', ["It's sunny today."]],
        ['Очень ветрено.', 'It is very windy.', ["It's very windy."]],
        ['Вчера было холодно.', 'Yesterday it was cold.', []],
      ],
    },
    {
      title: 'What is the weather like?',
      summary: 'Главный вопрос о погоде.',
      topics: [W, Q],
      dialogue: ['Звонок из другого города', [
        ['Ben', 'What is the weather like there?', 'Какая у вас там погода?'],
        ['Anna', 'Rainy and grey.', 'Дождливо и серо.'],
        ['Ben', 'Here it is twenty degrees.', 'А здесь двадцать градусов.'],
        ['Anna', 'Lucky you!', 'Везёт же!'],
        ['Ben', 'Come and visit.', 'Приезжай в гости.'],
      ]],
      words: [
        ['What is the weather like?', 'Какая погода?', 'What is the weather like today?'],
        ['rainy', 'дождливо', 'It is rainy.'],
        ['grey', 'серый, пасмурный', 'Grey and cold.'],
        ['twenty degrees', 'двадцать градусов', 'It is twenty degrees.'],
        ['Lucky you!', 'Везёт же!', 'Twenty degrees? Lucky you!'],
      ],
      rule: ['What is it like — «какое оно»', 'Тот же оборот, что и о человеке: what is she like. Про погоду — what is the weather like. Слово like здесь не «нравится», а «подобно», и переводить его отдельно не нужно.'],
      quiz: [
        ['«Какая погода?» —', ['What is the weather like?', 'How is the weather like?', 'What weather is it like?'], 0],
        ['«Двадцать градусов» —', ['twenty degrees', 'twenty degree', 'twenty of degrees'], 0],
        ['«Дождливо и серо» —', ['Rainy and grey', 'Rain and grey it', 'Rainy and a grey'], 0],
      ],
      order: ['Какая у вас там погода?', 'What is the weather like there?'],
      produce: [
        ['Какая сегодня погода?', 'What is the weather like today?', []],
        ['Дождливо и серо.', 'Rainy and grey.', []],
        ['Здесь двадцать градусов.', 'It is twenty degrees here.', ["It's twenty degrees here."]],
      ],
    },
    {
      title: 'Seasons',
      summary: 'Четыре времени года.',
      topics: [W, 'a1-prepositions-time'],
      dialogue: ['Любимое время года', [
        ['Anna', 'What is your favourite season?', 'Какое твоё любимое время года?'],
        ['Ben', 'Autumn. Not too hot, not too cold.', 'Осень. Не жарко и не холодно.'],
        ['Anna', 'I like summer.', 'Я люблю лето.'],
        ['Ben', 'In summer I go to the sea.', 'Летом я езжу на море.'],
        ['Anna', 'Me too, every year.', 'Я тоже, каждый год.'],
      ]],
      words: [
        ['a season', 'время года', 'My favourite season.'],
        ['spring', 'весна', 'In spring it is warm.'],
        ['summer', 'лето', 'I like summer.'],
        ['autumn', 'осень', 'Autumn is my season.'],
        ['winter', 'зима', 'Winter is long here.'],
      ],
      rule: ['In summer, in winter', 'Времена года идут с in: in summer, in winter, in spring. Артикль не нужен, если речь о времени года вообще. Он появляется в разговоре о конкретном: in the summer of 2025.'],
      quiz: [
        ['«Летом» —', ['in summer', 'on summer', 'at summer'], 0],
        ['«Осень» —', ['autumn', 'autum', 'the fall autumn'], 0],
        ['«Зима здесь длинная» —', ['Winter is long here', 'The winter is long here it', 'Winter here is a long'], 0],
      ],
      order: ['Летом я езжу на море.', 'In summer I go to the sea.'],
      produce: [
        ['Какое твоё любимое время года?', 'What is your favourite season?', []],
        ['Летом я езжу на море.', 'In summer I go to the sea.', []],
        ['Зима здесь длинная.', 'Winter is long here.', []],
      ],
    },
    {
      title: 'It is going to rain',
      summary: 'Первое будущее: going to.',
      topics: [W, L],
      dialogue: ['Прогноз', [
        ['Ben', 'Look at the sky. It is going to rain.', 'Посмотри на небо. Будет дождь.'],
        ['Anna', 'Are you sure?', 'Уверен?'],
        ['Ben', 'Very dark clouds.', 'Очень тёмные тучи.'],
        ['Anna', 'Then I am going to take an umbrella.', 'Тогда возьму зонт.'],
        ['Ben', 'Good idea.', 'Хорошая мысль.'],
      ]],
      words: [
        ['going to rain', 'будет дождь', 'It is going to rain.'],
        ['a sky', 'небо', 'Look at the sky.'],
        ['a cloud', 'облако, туча', 'Dark clouds.'],
        ['dark', 'тёмный', 'Very dark clouds.'],
        ['a good idea', 'хорошая мысль', 'That is a good idea.'],
      ],
      rule: ['Going to — то, к чему всё идёт', 'Форма проста: am/is/are + going to + глагол. Значит либо намерение (I am going to take an umbrella), либо очевидный прогноз по признакам (it is going to rain — тучи уже видно). Это самое употребимое будущее в разговоре.'],
      quiz: [
        ['«Будет дождь» —', ['It is going to rain', 'It is go to rain', 'It going to rain'], 0],
        ['«Я возьму зонт» (намерение) —', ['I am going to take an umbrella', 'I am go to take an umbrella', 'I going take an umbrella'], 0],
        ['«Тёмные тучи» —', ['dark clouds', 'a dark clouds', 'darks cloud'], 0],
      ],
      order: ['Будет дождь.', 'It is going to rain.'],
      produce: [
        ['Будет дождь.', 'It is going to rain.', ["It's going to rain."]],
        ['Я возьму зонт.', 'I am going to take an umbrella.', ["I'm going to take an umbrella."]],
        ['Хорошая мысль.', 'That is a good idea.', ["That's a good idea."]],
      ],
    },
    {
      title: 'What are you going to do?',
      summary: 'Планы на выходные.',
      topics: [L, Q, W],
      dialogue: ['Выходные', [
        ['Anna', 'What are you going to do on Sunday?', 'Что собираешься делать в воскресенье?'],
        ['Ben', 'If it is sunny, go to the park.', 'Если будет солнечно — в парк.'],
        ['Anna', 'And if it rains?', 'А если дождь?'],
        ['Ben', 'Stay home and watch films.', 'Останусь дома смотреть кино.'],
        ['Anna', 'Both sound good.', 'Оба варианта хороши.'],
      ]],
      words: [
        ['What are you going to do?', 'Что собираешься делать?', 'What are you going to do today?'],
        ['if', 'если', 'If it is sunny.'],
        ['stay home', 'остаться дома', 'Stay home and rest.'],
        ['a park', 'парк', 'Go to the park.'],
        ['both', 'оба', 'Both sound good.'],
      ],
      rule: ['После if — настоящее время', 'If it rains tomorrow, I stay home. По-русски мы говорим «если будет дождь», по-английски будущее после if не ставят: if it rains, а не if it will rain. Правило жёсткое и на слух заметное.'],
      quiz: [
        ['«Если завтра будет дождь» —', ['If it rains tomorrow', 'If it will rain tomorrow', 'If it is going to rain will'], 0],
        ['«Что собираешься делать?» —', ['What are you going to do?', 'What you are going to do?', 'What are you going do?'], 0],
        ['«Останусь дома» —', ['Stay home', 'Stay at the home', 'Stay in home'], 0],
      ],
      order: ['Что собираешься делать в воскресенье?', 'What are you going to do on Sunday?'],
      produce: [
        ['Если будет солнечно, пойду в парк.', 'If it is sunny, I go to the park.', []],
        ['Останусь дома.', 'I stay home.', []],
        ['Оба варианта хороши.', 'Both sound good.', []],
      ],
    },
    {
      title: 'Hot and cold',
      summary: 'Жара, мороз и как о них жалуются.',
      topics: [W, D],
      dialogue: ['Слишком жарко', [
        ['Ben', 'It is too hot today.', 'Сегодня слишком жарко.'],
        ['Anna', 'Thirty degrees!', 'Тридцать градусов!'],
        ['Ben', 'I cannot work in this heat.', 'Не могу работать в такую жару.'],
        ['Anna', 'Drink water and stay inside.', 'Пей воду и сиди внутри.'],
        ['Ben', 'Good advice.', 'Хороший совет.'],
      ]],
      words: [
        ['hot', 'жаркий', 'It is too hot.'],
        ['heat', 'жара', 'In this heat.'],
        ['freezing', 'очень холодно', 'It is freezing outside.'],
        ['snow', 'снег', 'A lot of snow.'],
        ['advice', 'совет', 'Good advice.'],
      ],
      rule: ['Advice не считают', 'Advice — «совет» вообще, множественного числа нет: good advice, a lot of advice. Один совет — a piece of advice. Так же устроены information, news, furniture: они всегда в единственном.'],
      quiz: [
        ['«Хороший совет» —', ['good advice', 'a good advice', 'good advices'], 0],
        ['«Очень холодно» —', ['It is freezing', 'It is freeze', 'There is freezing'], 0],
        ['«Много снега» —', ['a lot of snow', 'a lot of snows', 'many snow'], 0],
      ],
      order: ['Сегодня слишком жарко.', 'It is too hot today.'],
      produce: [
        ['Тридцать градусов!', 'Thirty degrees!', []],
        ['На улице очень холодно.', 'It is freezing outside.', ["It's freezing outside."]],
        ['Хороший совет.', 'Good advice.', []],
      ],
    },
    {
      title: 'Small talk about weather',
      summary: 'Как начать разговор с незнакомым.',
      topics: [W, G],
      dialogue: ['В очереди', [
        ['Незнакомец', 'Terrible weather, isn\'t it?', 'Ужасная погода, правда?'],
        ['Anna', 'Yes, awful. And so cold.', 'Да, кошмар. И так холодно.'],
        ['Незнакомец', 'They say it gets better tomorrow.', 'Говорят, завтра будет лучше.'],
        ['Anna', 'I hope so!', 'Надеюсь!'],
        ['Незнакомец', 'Have a good day.', 'Хорошего дня.'],
      ]],
      words: [
        ['terrible', 'ужасный', 'Terrible weather.'],
        ['awful', 'кошмарный', 'Awful, yes.'],
        ['They say…', 'Говорят …', 'They say it gets better.'],
        ['gets better', 'станет лучше', 'It gets better tomorrow.'],
        ['I hope so!', 'Надеюсь!', 'Tomorrow? I hope so!'],
      ],
      rule: ['Погода как приглашение к разговору', 'В Британии фраза о погоде — не сообщение, а способ начать разговор с незнакомым. Ответ по существу не нужен: достаточно согласиться и добавить свою реплику. Промолчать — значит закрыть разговор.'],
      quiz: [
        ['«Ужасная погода» —', ['Terrible weather', 'A terrible weather', 'The weather terrible'], 0],
        ['«Говорят, завтра лучше» —', ['They say it gets better tomorrow', 'They say tomorrow gets better it', 'It says they better tomorrow'], 0],
        ['«Надеюсь!» —', ['I hope so!', 'I hope it so!', 'I am hoping so!'], 0],
      ],
      order: ['Говорят, завтра будет лучше.', 'They say it gets better tomorrow.'],
      produce: [
        ['Ужасная погода.', 'Terrible weather.', []],
        ['И так холодно.', 'And so cold.', []],
        ['Надеюсь!', 'I hope so!', []],
      ],
    },
    {
      title: 'Weather and clothes',
      summary: 'Что надеть по погоде.',
      topics: [W, 'a1-tema-shopping'],
      dialogue: ['Перед выходом', [
        ['Anna', 'Take a coat, it is cold.', 'Возьми пальто, холодно.'],
        ['Ben', 'And an umbrella?', 'И зонт?'],
        ['Anna', 'Yes, it is going to rain.', 'Да, будет дождь.'],
        ['Ben', 'Boots too, then.', 'Тогда и ботинки.'],
        ['Anna', 'Now you are ready.', 'Вот теперь готов.'],
      ]],
      words: [
        ['boots', 'ботинки, сапоги', 'Take your boots.'],
        ['a scarf', 'шарф', 'A warm scarf.'],
        ['gloves', 'перчатки', 'Where are my gloves?'],
        ['a hat', 'шапка', 'Wear a hat.'],
        ['warm clothes', 'тёплая одежда', 'Warm clothes for winter.'],
      ],
      rule: ['Парные вещи всегда во множественном', 'Boots, gloves, socks — их два, и говорят о них во множественном: my gloves are here. Одна штука — a glove, но это редкий случай, обычно речь о паре.'],
      quiz: [
        ['«Где мои перчатки?» —', ['Where are my gloves?', 'Where is my gloves?', 'Where are my glove?'], 0],
        ['«Надень шапку» —', ['Wear a hat', 'Wear the hat on', 'Put a hat'], 0],
        ['«Тёплая одежда» —', ['warm clothes', 'a warm clothes', 'warm cloth'], 0],
      ],
      order: ['Возьми пальто, холодно.', 'Take a coat, it is cold.'],
      produce: [
        ['Возьми зонт.', 'Take an umbrella.', []],
        ['Где мои перчатки?', 'Where are my gloves?', []],
        ['Тёплая одежда на зиму.', 'Warm clothes for winter.', []],
      ],
    },
    {
      title: 'The forecast',
      summary: 'Прогноз погоды и как его читают.',
      topics: [W, 'a1-tema-contact'],
      dialogue: ['Смотрим прогноз', [
        ['Ben', 'What does the forecast say?', 'Что говорит прогноз?'],
        ['Anna', 'Rain in the morning, sun later.', 'Утром дождь, потом солнце.'],
        ['Ben', 'And the weekend?', 'А выходные?'],
        ['Anna', 'Dry and warm, they say.', 'Говорят, сухо и тепло.'],
        ['Ben', 'Then we go to the sea.', 'Тогда едем на море.'],
      ]],
      words: [
        ['a forecast', 'прогноз', 'What does the forecast say?'],
        ['dry', 'сухой', 'Dry and warm.'],
        ['wet', 'мокрый', 'The street is wet.'],
        ['later', 'позже', 'Sun later.'],
        ['a sea', 'море', 'Go to the sea.'],
      ],
      rule: ['Прогноз говорит', 'The forecast says, the app says, they say — по-английски источник «говорит» сам. Русское «в прогнозе написано» переводится именно так, а не через it is written.'],
      quiz: [
        ['«Что говорит прогноз?» —', ['What does the forecast say?', 'What says the forecast?', 'What do the forecast say?'], 0],
        ['«Сухо и тепло» —', ['Dry and warm', 'A dry and warm', 'Dryly and warm'], 0],
        ['«Улица мокрая» —', ['The street is wet', 'The street is a wet', 'The wet is street'], 0],
      ],
      order: ['Утром дождь, потом солнце.', 'Rain in the morning, sun later.'],
      produce: [
        ['Что говорит прогноз?', 'What does the forecast say?', []],
        ['Сухо и тепло.', 'Dry and warm.', []],
        ['Тогда едем на море.', 'Then we go to the sea.', []],
      ],
    },
    {
      title: 'Weather and travel',
      summary: 'Когда погода мешает поездке.',
      topics: [W, T, 'a1-tema-problems'],
      dialogue: ['Задержка рейса', [
        ['Anna', 'The flight is late because of the snow.', 'Рейс задерживается из-за снега.'],
        ['Ben', 'How long?', 'Насколько?'],
        ['Anna', 'Two hours, maybe more.', 'На два часа, может, больше.'],
        ['Ben', 'Nothing to do about it.', 'Ничего не поделаешь.'],
        ['Anna', 'Let us have a coffee then.', 'Тогда выпьем кофе.'],
      ]],
      words: [
        ['a flight', 'рейс', 'The flight is late.'],
        ['late', 'опаздывающий', 'The flight is late.'],
        ['because of', 'из-за', 'Because of the snow.'],
        ['maybe more', 'может, больше', 'Two hours, maybe more.'],
        ['Nothing to do.', 'Ничего не поделаешь.', 'Nothing to do about it.'],
      ],
      rule: ['Because of — только с существительным', 'Because of the snow, because of the rain. Целое предложение требует просто because: because it is snowing. Английский здесь строг, а по-русски «из-за» покрывает оба случая.'],
      quiz: [
        ['«Из-за снега» —', ['because of the snow', 'because the snow', 'for because snow'], 0],
        ['«Рейс задерживается» —', ['The flight is late', 'The flight is a late', 'The flight lates'], 0],
        ['«Ничего не поделаешь» —', ['Nothing to do about it', 'Nothing for do about it', 'No thing to do it about'], 0],
      ],
      order: ['Рейс задерживается из-за снега.', 'The flight is late because of the snow.'],
      produce: [
        ['Рейс задерживается.', 'The flight is late.', []],
        ['Из-за снега.', 'Because of the snow.', []],
        ['Ничего не поделаешь.', 'Nothing to do about it.', []],
      ],
    },
    {
      title: 'A perfect day',
      summary: 'Описать идеальную погоду и день.',
      topics: [W, L, D],
      dialogue: ['Идеальный день', [
        ['Ben', 'What is a perfect day for you?', 'Какой для тебя идеальный день?'],
        ['Anna', 'Sunny, twenty-two degrees, no wind.', 'Солнечно, двадцать два градуса, без ветра.'],
        ['Ben', 'And what do you do?', 'И что ты делаешь?'],
        ['Anna', 'Coffee outside and a long walk.', 'Кофе на улице и долгая прогулка.'],
        ['Ben', 'That is my perfect day too.', 'У меня такой же идеальный день.'],
      ]],
      words: [
        ['perfect', 'идеальный', 'A perfect day.'],
        ['no wind', 'без ветра', 'Sunny, no wind.'],
        ['a walk', 'прогулка', 'A long walk.'],
        ['outside', 'на улице', 'Coffee outside.'],
        ['for you', 'для тебя', 'A perfect day for you.'],
      ],
      rule: ['No вместо not any', 'No wind, no sugar, no problem — короткая форма отрицания перед существительным. Полный вариант there is not any wind тоже верен, но в живой речи почти всегда говорят коротко.'],
      quiz: [
        ['«Без ветра» —', ['no wind', 'not wind', 'no any wind'], 0],
        ['«Долгая прогулка» —', ['a long walk', 'a walk long', 'the long of walk'], 0],
        ['«Для тебя» —', ['for you', 'to you', 'of you'], 0],
      ],
      order: ['Солнечно, двадцать два градуса, без ветра.', 'Sunny, twenty-two degrees, no wind.'],
      produce: [
        ['Какой для тебя идеальный день?', 'What is a perfect day for you?', []],
        ['Кофе на улице и долгая прогулка.', 'Coffee outside and a long walk.', []],
        ['Без ветра.', 'No wind.', []],
      ],
    },
    {
      title: 'Weather in my country',
      summary: 'Рассказать о климате там, где живёшь.',
      topics: [W, 'a1-tema-travel', D],
      dialogue: ['Про климат', [
        ['Ben', 'What is the weather like in {country}?', 'Какая погода в {страна}?'],
        ['Anna', 'Cold winters, warm summers.', 'Холодные зимы, тёплое лето.'],
        ['Ben', 'How cold in winter?', 'Насколько холодно зимой?'],
        ['Anna', 'Minus ten, sometimes more.', 'Минус десять, иногда больше.'],
        ['Ben', 'That is really cold!', 'Это правда холодно!'],
      ]],
      words: [
        ['a winter', 'зима', 'Cold winters.'],
        ['minus ten', 'минус десять', 'Minus ten in winter.'],
        ['sometimes', 'иногда', 'Sometimes more.'],
        ['a climate', 'климат', 'A cold climate.'],
        ['really', 'правда, действительно', 'That is really cold.'],
      ],
      rule: ['Множественное для повторяющегося', 'Cold winters, warm summers — множественное, потому что речь о каждой зиме и каждом лете, а не об одной. Русский тут обходится единственным, и это заметная разница в описании климата.'],
      quiz: [
        ['«Холодные зимы» —', ['cold winters', 'a cold winters', 'cold winter every'], 0],
        ['«Минус десять» —', ['minus ten', 'less ten', 'minus of ten'], 0],
        ['«Это правда холодно» —', ['That is really cold', 'That is real cold', 'It is really a cold'], 0],
      ],
      order: ['Холодные зимы, тёплое лето.', 'Cold winters, warm summers.'],
      produce: [
        ['Какая погода в {страна}?', 'What is the weather like in {country}?', []],
        ['Холодные зимы, тёплое лето.', 'Cold winters, warm summers.', []],
        ['Иногда минус десять.', 'Sometimes minus ten.', []],
      ],
    },
    {
      title: 'Changing weather',
      summary: 'Погода меняется прямо сейчас.',
      topics: [W, 'a1-present-continuous'],
      dialogue: ['Меняется на глазах', [
        ['Anna', 'It is getting colder.', 'Холодает.'],
        ['Ben', 'And the wind is getting stronger.', 'И ветер усиливается.'],
        ['Anna', 'The sky is getting dark.', 'Небо темнеет.'],
        ['Ben', 'Let us go inside.', 'Пойдём внутрь.'],
        ['Anna', 'Quickly!', 'Быстрее!'],
      ]],
      words: [
        ['getting colder', 'холодает', 'It is getting colder.'],
        ['stronger', 'сильнее', 'The wind is getting stronger.'],
        ['quickly', 'быстро', 'Quickly, please!'],
        ['inside', 'внутрь, внутри', 'Let us go inside.'],
        ['a wind', 'ветер', 'The wind is cold.'],
      ],
      rule: ['Get + сравнительная = «становится»', 'It is getting colder, warmer, darker, better. Глагол get здесь значит «становиться», и в связке со сравнительной формой описывает изменение прямо сейчас. Одна из самых частых конструкций живой речи.'],
      quiz: [
        ['«Холодает» —', ['It is getting colder', 'It is getting cold more', 'It gets more cold now'], 0],
        ['«Ветер усиливается» —', ['The wind is getting stronger', 'The wind gets more strong is', 'The wind is stronger getting'], 0],
        ['«Пойдём внутрь» —', ['Let us go inside', 'Let us go in inside', 'Go we inside'], 0],
      ],
      order: ['Небо темнеет.', 'The sky is getting dark.'],
      produce: [
        ['Холодает.', 'It is getting colder.', ["It's getting colder."]],
        ['Ветер усиливается.', 'The wind is getting stronger.', []],
        ['Пойдём внутрь.', 'Let us go inside.', ["Let's go inside."]],
      ],
    },
    {
      title: 'Weather words in the news',
      summary: 'Как о погоде пишут коротко.',
      topics: [W, 'a1-tema-contact', D],
      dialogue: ['Сводка', [
        ['Anna', 'The app says storm tonight.', 'Приложение пишет: ночью шторм.'],
        ['Ben', 'A storm? Really?', 'Шторм? Серьёзно?'],
        ['Anna', 'Strong wind and heavy rain.', 'Сильный ветер и ливень.'],
        ['Ben', 'Then we stay at home.', 'Тогда сидим дома.'],
        ['Anna', 'Definitely.', 'Точно.'],
      ]],
      words: [
        ['a storm', 'шторм, гроза', 'A storm tonight.'],
        ['strong wind', 'сильный ветер', 'Strong wind today.'],
        ['heavy rain', 'ливень', 'Heavy rain expected.'],
        ['tonight', 'сегодня ночью', 'Storm tonight.'],
        ['Definitely.', 'Точно.', 'Definitely, yes.'],
      ],
      rule: ['Heavy rain, strong wind', 'Дождь бывает heavy, а ветер strong — и наоборот не говорят. Такие устойчивые пары называют коллокациями, и запоминать их надо целиком: big rain звучит для англичанина так же странно, как «сильный дождик» для нас.'],
      quiz: [
        ['«Ливень» —', ['heavy rain', 'strong rain', 'big rain'], 0],
        ['«Сильный ветер» —', ['strong wind', 'heavy wind', 'big wind'], 0],
        ['«Сегодня ночью» —', ['tonight', 'this night', 'in the tonight'], 0],
      ],
      order: ['Сильный ветер и ливень.', 'Strong wind and heavy rain.'],
      produce: [
        ['Ночью шторм.', 'A storm tonight.', []],
        ['Сильный ветер и ливень.', 'Strong wind and heavy rain.', []],
        ['Тогда сидим дома.', 'Then we stay at home.', []],
      ],
    },
    {
      title: 'Plans depend on weather',
      summary: 'Два плана: на солнце и на дождь.',
      topics: [W, L, Q],
      dialogue: ['План Б', [
        ['Ben', 'Picnic on Saturday?', 'Пикник в субботу?'],
        ['Anna', 'If the weather is good, yes.', 'Если погода будет хорошая, да.'],
        ['Ben', 'And if not?', 'А если нет?'],
        ['Anna', 'Then a museum. Plan B.', 'Тогда музей. План Б.'],
        ['Ben', 'Perfect, both work.', 'Отлично, оба варианта годятся.'],
      ]],
      words: [
        ['a picnic', 'пикник', 'A picnic on Saturday.'],
        ['If the weather is good', 'Если погода хорошая', 'If the weather is good, we go.'],
        ['and if not', 'а если нет', 'And if not, a museum.'],
        ['plan B', 'запасной план', 'Then plan B.'],
        ['both work', 'оба годятся', 'Both work for me.'],
      ],
      rule: ['Запасной план в одну фразу', 'If the weather is good, a picnic. If not, a museum. Английский любит короткие условные пары, и на A1 их достаточно, чтобы договориться о чём угодно — без всякого будущего времени.'],
      quiz: [
        ['«Если погода хорошая» —', ['If the weather is good', 'If the weather will be good', 'If weather is good'], 0],
        ['«А если нет?» —', ['And if not?', 'And if no?', 'And if it not?'], 0],
        ['«Оба годятся» —', ['Both work', 'Both works', 'The both work'], 0],
      ],
      order: ['Если погода будет хорошая, да.', 'If the weather is good, yes.'],
      produce: [
        ['Пикник в субботу?', 'A picnic on Saturday?', []],
        ['Если погода хорошая, да.', 'If the weather is good, yes.', []],
        ['Тогда музей.', 'Then a museum.', []],
      ],
    },
    {
      title: 'A year of weather',
      summary: 'Весь блок: год в четырёх предложениях.',
      topics: [W, D, L],
      dialogue: ['Год целиком', [
        ['Anna', 'In spring it is wet but warm.', 'Весной сыро, но тепло.'],
        ['Ben', 'Summer?', 'Летом?'],
        ['Anna', 'Hot and dry. Everybody goes to the sea.', 'Жарко и сухо. Все едут на море.'],
        ['Ben', 'And winter is cold, I know.', 'А зима холодная, я знаю.'],
        ['Anna', 'Autumn is my favourite: quiet and golden.', 'Осень моя любимая: тихая и золотая.'],
      ]],
      words: [
        ['golden', 'золотой', 'Golden autumn.'],
        ['quiet', 'тихий', 'Quiet and golden.'],
        ['everybody', 'все', 'Everybody goes to the sea.'],
        ['in spring', 'весной', 'In spring it is warm.'],
        ['I know', 'я знаю', 'Winter is cold, I know.'],
      ],
      rule: ['Год в четырёх предложениях', 'По одному на время года — этого хватает, чтобы рассказать о климате целой страны. На A1 умение уложить тему в четыре простых предложения ценнее, чем длинная фраза с ошибками.'],
      quiz: [
        ['«Весной сыро, но тепло» —', ['In spring it is wet but warm', 'In the spring is wet but warm', 'Spring it is wet but warm'], 0],
        ['«Все едут на море» —', ['Everybody goes to the sea', 'Everybody go to the sea', 'All goes to the sea'], 0],
        ['«Золотая осень» —', ['golden autumn', 'gold autumn', 'the autumn golden'], 0],
      ],
      order: ['Весной сыро, но тепло.', 'In spring it is wet but warm.'],
      produce: [
        ['Летом жарко и сухо.', 'In summer it is hot and dry.', []],
        ['Все едут на море.', 'Everybody goes to the sea.', []],
        ['Осень моя любимая.', 'Autumn is my favourite.', []],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: погода',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [W, L, Q, D],
      produce: [
        ['Сегодня солнечно.', 'It is sunny today.', ["It's sunny today."]],
        ['Какая сегодня погода?', 'What is the weather like today?', []],
        ['Будет дождь.', 'It is going to rain.', ["It's going to rain."]],
        ['Если будет солнечно, пойду в парк.', 'If it is sunny, I go to the park.', []],
        ['Холодает.', 'It is getting colder.', ["It's getting colder."]],
        ['Холодные зимы, тёплое лето.', 'Cold winters, warm summers.', []],
      ],
    },
  ],
}
