// Блок 15 — Health. Сказать, что болит, и сходить в аптеку.
//
// Тема, которую откладывают до последнего, а нужна она внезапно и сразу. Поэтому здесь
// не медицинская лексика, а десяток фраз, которых хватает: что болит, как давно, что
// принимать, где аптека, вызвать врача.

const HE = 'a1-tema-health'
const HG = 'a1-have-got'
const B = 'a1-to-be'
const Q = 'a1-questions'
const C = 'a1-can'
const P = 'a1-tema-problems'
const CITY = 'a1-tema-city'

export default {
  slug: 'health',
  title: 'Health',
  subtitle: 'Сказать, что болит, купить лекарство и вызвать врача',
  canDo: [
    'сказать, что у тебя болит',
    'описать самочувствие',
    'купить лекарство в аптеке',
    'записаться к врачу',
    'позвать на помощь в срочном случае',
  ],
  lessons: [
    {
      title: 'I have got a headache',
      summary: 'Как сказать, что болит.',
      topics: [HE, HG],
      dialogue: ['Плохо себя чувствую', [
        ['Anna', 'I have got a headache.', 'У меня болит голова.'],
        ['Ben', 'Since when?', 'С каких пор?'],
        ['Anna', 'Since this morning.', 'С утра.'],
        ['Ben', 'Take a pill and rest.', 'Прими таблетку и отдохни.'],
        ['Anna', 'Yes, I think I will.', 'Да, пожалуй.'],
      ]],
      words: [
        ['a headache', 'головная боль', 'I have got a headache.'],
        ['a toothache', 'зубная боль', 'A bad toothache.'],
        ['a stomach ache', 'боль в животе', 'A stomach ache since morning.'],
        ['a pill', 'таблетка', 'Take a pill.'],
        ['since this morning', 'с утра', 'Since this morning.'],
      ],
      rule: ['Боль — через have got', 'I have got a headache, a toothache, a cold. Не «мне болит», а «я имею боль». Русская конструкция «у меня болит голова» переводится именно так, и слово ache уже содержит «боль».'],
      quiz: [
        ['«У меня болит голова» —', ['I have got a headache', 'My head is ache', 'I am headache'], 0],
        ['«С утра» —', ['since this morning', 'from this morning since', 'in this morning'], 0],
        ['«Прими таблетку» —', ['Take a pill', 'Drink a pill', 'Eat the pill'], 0],
      ],
      order: ['У меня болит голова.', 'I have got a headache.'],
      produce: [
        ['У меня болит голова.', 'I have got a headache.', ['I have a headache.']],
        ['С утра.', 'Since this morning.', []],
        ['Прими таблетку.', 'Take a pill.', []],
      ],
    },
    {
      title: 'My back hurts',
      summary: 'Второй способ: что-то болит само.',
      topics: [HE, B],
      dialogue: ['Спина', [
        ['Ben', 'My back hurts.', 'У меня болит спина.'],
        ['Anna', 'Where exactly?', 'Где именно?'],
        ['Ben', 'Here, on the left.', 'Вот здесь, слева.'],
        ['Anna', 'Do not lift heavy things.', 'Не поднимай тяжёлое.'],
        ['Ben', 'Too late for that.', 'Поздновато для этого.'],
      ]],
      words: [
        ['hurts', 'болит', 'My back hurts.'],
        ['a back', 'спина', 'My back hurts.'],
        ['a leg', 'нога', 'My leg hurts.'],
        ['an arm', 'рука', 'My arm hurts.'],
        ['lift', 'поднимать', 'Do not lift heavy things.'],
      ],
      rule: ['Два способа сказать о боли', 'I have got a headache — через существительное. My head hurts — через глагол. Оба нормальны, но части тела чаще идут с hurts: my back hurts, my legs hurt. И заметьте: подлежащее — часть тела, а не человек.'],
      quiz: [
        ['«У меня болит спина» —', ['My back hurts', 'I hurt my back is', 'My back is hurt'], 0],
        ['«Ноги болят» —', ['My legs hurt', 'My legs hurts', 'My leg hurt'], 0],
        ['«Не поднимай тяжёлое» —', ['Do not lift heavy things', 'Do not lift heavy', 'Not lift the heavy things'], 0],
      ],
      order: ['У меня болит спина.', 'My back hurts.'],
      produce: [
        ['У меня болит нога.', 'My leg hurts.', []],
        ['Где именно?', 'Where exactly?', []],
        ['Не поднимай тяжёлое.', 'Do not lift heavy things.', []],
      ],
    },
    {
      title: 'I have got a cold',
      summary: 'Простуда и температура.',
      topics: [HE, HG],
      dialogue: ['Простыл', [
        ['Anna', 'You sound terrible.', 'Голос у тебя ужасный.'],
        ['Ben', 'I have got a cold.', 'Я простыл.'],
        ['Anna', 'Have you got a temperature?', 'Температура есть?'],
        ['Ben', 'A little. Thirty-seven five.', 'Небольшая. Тридцать семь и пять.'],
        ['Anna', 'Stay home today.', 'Останься сегодня дома.'],
      ]],
      words: [
        ['a cold', 'простуда', 'I have got a cold.'],
        ['a temperature', 'температура', 'Have you got a temperature?'],
        ['a cough', 'кашель', 'A bad cough.'],
        ['flu', 'грипп', 'It is flu, not a cold.'],
        ['You sound terrible.', 'Голос у тебя ужасный.', 'You sound terrible today.'],
      ],
      rule: ['A cold и cold', 'A cold с артиклем — простуда. Cold без артикля — холодно: I am cold. Разница в одну букву, а перепутать легко: I have got a cold значит «я простыл», а I am cold — «мне холодно».'],
      quiz: [
        ['«Я простыл» —', ['I have got a cold', 'I am cold', 'I have cold'], 0],
        ['«Мне холодно» —', ['I am cold', 'I have got a cold', 'I have cold to me'], 0],
        ['«Температура есть?» —', ['Have you got a temperature?', 'Do you have got temperature?', 'Are you have temperature?'], 0],
      ],
      order: ['У меня простуда.', 'I have got a cold.'],
      produce: [
        ['Я простыл.', 'I have got a cold.', ['I have a cold.']],
        ['Мне холодно.', 'I am cold.', ["I'm cold."]],
        ['Останься сегодня дома.', 'Stay home today.', []],
      ],
    },
    {
      title: 'At the pharmacy',
      summary: 'Купить лекарство без рецепта.',
      topics: [HE, 'a1-tema-shopping', C],
      dialogue: ['В аптеке', [
        ['Anna', 'Something for a headache, please.', 'Что-нибудь от головной боли.'],
        ['Фармацевт', 'These are good. Two a day.', 'Вот эти хорошие. Два раза в день.'],
        ['Anna', 'With food or without?', 'С едой или без?'],
        ['Фармацевт', 'With food, better.', 'Лучше с едой.'],
        ['Anna', 'Thank you. How much?', 'Спасибо. Сколько?'],
      ]],
      words: [
        ['Something for a headache', 'что-нибудь от головной боли', 'Something for a headache, please.'],
        ['medicine', 'лекарство', 'This medicine is strong.'],
        ['two a day', 'два раза в день', 'Two a day, with food.'],
        ['with food', 'с едой', 'Take it with food.'],
        ['a pharmacy', 'аптека', 'The pharmacy is open.'],
      ],
      rule: ['Something for — «что-нибудь от»', 'В аптеке не нужно знать название: something for a headache, something for a cough. Фармацевт подберёт сам. Это самая полезная фраза блока и работает в любой стране.'],
      quiz: [
        ['«Что-нибудь от кашля» —', ['Something for a cough', 'Something from a cough', 'Something against cough'], 0],
        ['«Два раза в день» —', ['two a day', 'two in a day', 'two of day'], 0],
        ['«С едой» —', ['with food', 'by food', 'on food'], 0],
      ],
      order: ['Что-нибудь от головной боли, пожалуйста.', 'Something for a headache, please.'],
      produce: [
        ['Что-нибудь от кашля, пожалуйста.', 'Something for a cough, please.', []],
        ['Два раза в день.', 'Two a day.', []],
        ['С едой или без?', 'With food or without?', []],
      ],
    },
    {
      title: 'I need a doctor',
      summary: 'Записаться к врачу.',
      topics: [HE, Q, 'a1-tema-meetings'],
      dialogue: ['Запись', [
        ['Anna', 'I need to see a doctor.', 'Мне нужно к врачу.'],
        ['Регистратор', 'Today at four or tomorrow morning?', 'Сегодня в четыре или завтра утром?'],
        ['Anna', 'Today, please. It is urgent.', 'Сегодня, пожалуйста. Это срочно.'],
        ['Регистратор', 'Your name and date of birth?', 'Имя и дата рождения?'],
        ['Anna', 'Anna Sokolova, fifth of May.', 'Анна Соколова, пятое мая.'],
      ]],
      words: [
        ['see a doctor', 'сходить к врачу', 'I need to see a doctor.'],
        ['urgent', 'срочный', 'It is urgent.'],
        ['an appointment', 'запись, приём', 'I have an appointment.'],
        ['a date of birth', 'дата рождения', 'Your date of birth?'],
        ['fifth of May', 'пятое мая', 'The fifth of May.'],
      ],
      rule: ['See a doctor, not visit', 'К врачу «ходят посмотреть»: I see a doctor, I am seeing the doctor at four. Visit a doctor тоже поймут, но звучит книжно. И приём называют appointment — то же слово, что и деловая встреча.'],
      quiz: [
        ['«Мне нужно к врачу» —', ['I need to see a doctor', 'I need to visit at doctor', 'I need see a doctor'], 0],
        ['«Это срочно» —', ['It is urgent', 'It is a urgent', 'There is urgent'], 0],
        ['«У меня запись» —', ['I have an appointment', 'I have a appointment', 'I am on appointment'], 0],
      ],
      order: ['Мне нужно к врачу.', 'I need to see a doctor.'],
      produce: [
        ['Мне нужно к врачу.', 'I need to see a doctor.', []],
        ['Это срочно.', 'It is urgent.', ["It's urgent."]],
        ['У меня запись на четыре.', 'I have an appointment at four.', []],
      ],
    },
    {
      title: 'How do you feel?',
      summary: 'Спросить о самочувствии и ответить.',
      topics: [HE, Q, B],
      dialogue: ['Как ты', [
        ['Ben', 'How do you feel today?', 'Как ты сегодня?'],
        ['Anna', 'Better, thanks.', 'Лучше, спасибо.'],
        ['Ben', 'Still tired?', 'Всё ещё устала?'],
        ['Anna', 'A bit, but much better than yesterday.', 'Немного, но гораздо лучше, чем вчера.'],
        ['Ben', 'Good to hear.', 'Рад слышать.'],
      ]],
      words: [
        ['How do you feel?', 'Как самочувствие?', 'How do you feel today?'],
        ['better', 'лучше', 'Better, thanks.'],
        ['a bit', 'немного', 'A bit tired.'],
        ['much better', 'гораздо лучше', 'Much better than yesterday.'],
        ['Good to hear.', 'Рад слышать.', 'Better? Good to hear.'],
      ],
      rule: ['Feel без себя', 'I feel better, I feel tired — без возвратного слова. Русское «я чувствую себя» тянет за собой myself, но I feel myself по-английски значит совсем другое и звучит неловко.'],
      quiz: [
        ['«Я чувствую себя лучше» —', ['I feel better', 'I feel myself better', 'I am feeling myself better'], 0],
        ['«Гораздо лучше, чем вчера» —', ['much better than yesterday', 'more better than yesterday', 'much better that yesterday'], 0],
        ['«Рад слышать» —', ['Good to hear', 'Good for hear', 'Glad to hearing'], 0],
      ],
      order: ['Гораздо лучше, чем вчера.', 'Much better than yesterday.'],
      produce: [
        ['Как самочувствие?', 'How do you feel?', []],
        ['Лучше, спасибо.', 'Better, thanks.', []],
        ['Я немного устал.', 'I feel a bit tired.', []],
      ],
    },
    {
      title: 'You should rest',
      summary: 'Дать совет.',
      topics: [HE, C],
      dialogue: ['Совет', [
        ['Anna', 'You should rest.', 'Тебе надо отдохнуть.'],
        ['Ben', 'I have got a lot of work.', 'У меня много работы.'],
        ['Anna', 'You should not work today.', 'Сегодня работать не надо.'],
        ['Ben', 'Maybe you are right.', 'Может, ты и права.'],
        ['Anna', 'Drink water and sleep.', 'Пей воду и спи.'],
      ]],
      words: [
        ['should', 'следует, надо', 'You should rest.'],
        ['should not', 'не следует', 'You should not work today.'],
        ['rest', 'отдыхать', 'You should rest.'],
        ['a lot of work', 'много работы', 'I have got a lot of work.'],
        ['You are right.', 'Ты права.', 'Maybe you are right.'],
      ],
      rule: ['Should — мягкий совет', 'You should rest — «тебе стоит отдохнуть». После should глагол идёт без to: should rest, should go. Это не приказ, а совет, и потому им пользуются постоянно, в том числе с незнакомыми.'],
      quiz: [
        ['«Тебе надо отдохнуть» —', ['You should rest', 'You should to rest', 'You should resting'], 0],
        ['«Не надо работать» —', ['You should not work', 'You should not to work', 'You not should work'], 0],
        ['«Может, ты права» —', ['Maybe you are right', 'Maybe you have right', 'May be you right'], 0],
      ],
      order: ['Тебе надо отдохнуть.', 'You should rest.'],
      produce: [
        ['Тебе надо отдохнуть.', 'You should rest.', []],
        ['Сегодня работать не надо.', 'You should not work today.', ["You shouldn't work today."]],
        ['Пей воду и спи.', 'Drink water and sleep.', []],
      ],
    },
    {
      title: 'Parts of the body',
      summary: 'Названия, которых хватает.',
      topics: [HE, 'a1-plural'],
      dialogue: ['У врача', [
        ['Врач', 'Where does it hurt?', 'Где болит?'],
        ['Ben', 'My shoulder and my neck.', 'Плечо и шея.'],
        ['Врач', 'Since the accident?', 'После падения?'],
        ['Ben', 'Yes, since last week.', 'Да, с прошлой недели.'],
        ['Врач', 'Let me see.', 'Дайте посмотрю.'],
      ]],
      words: [
        ['a shoulder', 'плечо', 'My shoulder hurts.'],
        ['a neck', 'шея', 'My neck is stiff.'],
        ['a knee', 'колено', 'My knee hurts.'],
        ['a hand', 'кисть руки', 'My hand is cold.'],
        ['a foot', 'ступня', 'My foot hurts.'],
      ],
      rule: ['Foot и feet, tooth и teeth', 'Части тела дают самые известные неправильные множественные: foot — feet, tooth — teeth. Ещё пара: arm — рука от плеча, hand — кисть. Русское «рука» одно, английских два, и врач спросит именно уточняя.'],
      quiz: [
        ['Множественное от foot —', ['feet', 'foots', 'feets'], 0],
        ['«Кисть руки» —', ['a hand', 'an arm', 'a leg'], 0],
        ['«Где болит?» —', ['Where does it hurt?', 'Where it hurts?', 'Where do it hurt?'], 0],
      ],
      order: ['Плечо и шея.', 'My shoulder and my neck.'],
      produce: [
        ['У меня болит колено.', 'My knee hurts.', []],
        ['Где болит?', 'Where does it hurt?', []],
        ['С прошлой недели.', 'Since last week.', []],
      ],
    },
    {
      title: 'Call an ambulance',
      summary: 'Срочный случай.',
      topics: [HE, P, C],
      dialogue: ['Срочно', [
        ['Прохожий', 'Are you OK?', 'Вам плохо?'],
        ['Anna', 'No. Call an ambulance, please.', 'Нет. Вызовите скорую, пожалуйста.'],
        ['Прохожий', 'What is wrong?', 'Что случилось?'],
        ['Anna', 'My chest hurts. I cannot breathe well.', 'Болит грудь. Тяжело дышать.'],
        ['Прохожий', 'Sit down. Help is coming.', 'Сядьте. Помощь едет.'],
      ]],
      words: [
        ['an ambulance', 'скорая помощь', 'Call an ambulance.'],
        ['What is wrong?', 'Что случилось?', 'What is wrong with you?'],
        ['a chest', 'грудь', 'My chest hurts.'],
        ['breathe', 'дышать', 'I cannot breathe well.'],
        ['Help is coming.', 'Помощь едет.', 'Sit down, help is coming.'],
      ],
      rule: ['Три фразы на крайний случай', 'Call an ambulance, I cannot breathe, my chest hurts. Их заучивают наизусть и не разбирают: в такую минуту грамматика не вспоминается, а эти три предложения решают дело. Номер экстренных служб в Британии — 999, в Европе — 112.'],
      quiz: [
        ['«Вызовите скорую» —', ['Call an ambulance', 'Call the fast help', 'Call a ambulance'], 0],
        ['«Я не могу дышать» —', ['I cannot breathe', 'I cannot to breathe', 'I do not can breathe'], 0],
        ['Номер экстренных служб в Европе —', ['112', '911', '01'], 0],
      ],
      order: ['Вызовите скорую, пожалуйста.', 'Call an ambulance, please.'],
      produce: [
        ['Вызовите скорую.', 'Call an ambulance.', []],
        ['Болит грудь.', 'My chest hurts.', []],
        ['Что случилось?', 'What is wrong?', []],
      ],
    },
    {
      title: 'Insurance and papers',
      summary: 'Страховка и документы в клинике.',
      topics: [HE, 'a1-tema-travel', Q],
      dialogue: ['На стойке', [
        ['Регистратор', 'Do you have insurance?', 'У вас есть страховка?'],
        ['Ben', 'Yes, travel insurance. Here.', 'Да, туристическая. Вот.'],
        ['Регистратор', 'And your passport, please.', 'И паспорт, пожалуйста.'],
        ['Ben', 'How much is the visit?', 'Сколько стоит приём?'],
        ['Регистратор', 'Insurance covers it.', 'Страховка покрывает.'],
      ]],
      words: [
        ['insurance', 'страховка', 'Do you have insurance?'],
        ['travel insurance', 'туристическая страховка', 'I have travel insurance.'],
        ['a visit', 'приём, визит', 'How much is the visit?'],
        ['covers', 'покрывает', 'Insurance covers it.'],
        ['papers', 'документы', 'All papers are here.'],
      ],
      rule: ['Insurance не считают', 'Insurance — без артикля и без множественного: do you have insurance. Одна страховка как документ — an insurance policy. Так же устроены information, advice, luggage.'],
      quiz: [
        ['«У вас есть страховка?» —', ['Do you have insurance?', 'Do you have an insurance?', 'Have you insurances?'], 0],
        ['«Страховка покрывает» —', ['Insurance covers it', 'Insurance cover it', 'The insurance is cover it'], 0],
        ['«Сколько стоит приём?» —', ['How much is the visit?', 'How much the visit is?', 'How much cost visit?'], 0],
      ],
      order: ['У вас есть страховка?', 'Do you have insurance?'],
      produce: [
        ['У меня туристическая страховка.', 'I have travel insurance.', []],
        ['Сколько стоит приём?', 'How much is the visit?', []],
        ['Страховка покрывает.', 'Insurance covers it.', []],
      ],
    },
    {
      title: 'Feeling better',
      summary: 'Выздоровление и благодарность.',
      topics: [HE, B, 'a1-tema-greetings'],
      dialogue: ['Через неделю', [
        ['Ben', 'You look well today.', 'Ты сегодня хорошо выглядишь.'],
        ['Anna', 'I feel much better, thanks.', 'Чувствую себя гораздо лучше, спасибо.'],
        ['Ben', 'No more headaches?', 'Голова не болит?'],
        ['Anna', 'None. The pills helped.', 'Совсем. Таблетки помогли.'],
        ['Ben', 'Great news.', 'Отличная новость.'],
      ]],
      words: [
        ['You look well.', 'Ты хорошо выглядишь.', 'You look well today.'],
        ['much better', 'гораздо лучше', 'I feel much better.'],
        ['helped', 'помогли', 'The pills helped.'],
        ['None.', 'Совсем нет.', 'Headaches? None.'],
        ['news', 'новость, новости', 'Great news.'],
      ],
      rule: ['Good и well', 'You look good — хорошо выглядишь внешне. You look well — здоровым. О самочувствии говорят well: I feel well. А news, кстати, единственное число: the news is good.'],
      quiz: [
        ['«Ты выглядишь здоровым» —', ['You look well', 'You look good health', 'You are looking wellly'], 0],
        ['«Отличная новость» —', ['Great news', 'A great news', 'Great newses'], 0],
        ['«Таблетки помогли» —', ['The pills helped', 'The pills are helped', 'The pills help was'], 0],
      ],
      order: ['Чувствую себя гораздо лучше.', 'I feel much better.'],
      produce: [
        ['Ты хорошо выглядишь.', 'You look well.', []],
        ['Таблетки помогли.', 'The pills helped.', []],
        ['Отличная новость.', 'Great news.', []],
      ],
    },
    {
      title: 'Healthy habits',
      summary: 'Что делаешь для здоровья.',
      topics: [HE, 'a1-adverbs-frequency', 'a1-present-simple'],
      dialogue: ['Привычки', [
        ['Anna', 'Do you do sport?', 'Ты занимаешься спортом?'],
        ['Ben', 'I walk a lot. And I swim on Fridays.', 'Много хожу. И плаваю по пятницам.'],
        ['Anna', 'I never do sport, honestly.', 'Я спортом вообще не занимаюсь, честно.'],
        ['Ben', 'Walking is enough.', 'Ходьбы достаточно.'],
        ['Anna', 'Then I am fine!', 'Тогда я в порядке!'],
      ]],
      words: [
        ['do sport', 'заниматься спортом', 'Do you do sport?'],
        ['swim', 'плавать', 'I swim on Fridays.'],
        ['walking', 'ходьба', 'Walking is enough.'],
        ['healthy', 'здоровый, полезный', 'A healthy habit.'],
        ['a habit', 'привычка', 'A good habit.'],
      ],
      rule: ['Do sport или play sport', 'Британцы говорят do sport, американцы play sports. С конкретной игрой всегда play: play football, play tennis. А с бегом и плаванием — go: go running, go swimming.'],
      quiz: [
        ['«Играть в футбол» —', ['play football', 'do football', 'go football'], 0],
        ['«Ходить плавать» —', ['go swimming', 'do swimming', 'play swimming'], 0],
        ['«Ходьбы достаточно» —', ['Walking is enough', 'The walking is enough it', 'Walk is enough'], 0],
      ],
      order: ['Я плаваю по пятницам.', 'I swim on Fridays.'],
      produce: [
        ['Ты занимаешься спортом?', 'Do you do sport?', []],
        ['Я плаваю по пятницам.', 'I swim on Fridays.', []],
        ['Ходьбы достаточно.', 'Walking is enough.', []],
      ],
    },
    {
      title: 'At the dentist',
      summary: 'Зубной врач и боль.',
      topics: [HE, Q, C],
      dialogue: ['У стоматолога', [
        ['Врач', 'Which tooth hurts?', 'Какой зуб болит?'],
        ['Anna', 'This one, at the back.', 'Вот этот, сзади.'],
        ['Врач', 'Does it hurt with cold water?', 'От холодной воды болит?'],
        ['Anna', 'Yes, very much.', 'Да, очень.'],
        ['Врач', 'We can fix it today.', 'Сегодня и вылечим.'],
      ]],
      words: [
        ['a tooth', 'зуб', 'Which tooth hurts?'],
        ['at the back', 'сзади', 'This one, at the back.'],
        ['fix', 'починить, вылечить', 'We can fix it today.'],
        ['a dentist', 'стоматолог', 'I go to the dentist.'],
        ['very much', 'очень', 'It hurts very much.'],
      ],
      rule: ['Does it hurt?', 'В вопросе о третьем лице появляется does, и глагол теряет -s: does it hurt, а не does it hurts. Это первая ловушка третьего лица, и попадаются в неё почти все.'],
      quiz: [
        ['«Болит?» —', ['Does it hurt?', 'Does it hurts?', 'Do it hurt?'], 0],
        ['«Какой зуб болит?» —', ['Which tooth hurts?', 'Which tooth hurt?', 'Which the tooth hurts?'], 0],
        ['«Мы вылечим это сегодня» —', ['We can fix it today', 'We can to fix it today', 'We can fixing it today'], 0],
      ],
      order: ['Какой зуб болит?', 'Which tooth hurts?'],
      produce: [
        ['Вот этот, сзади.', 'This one, at the back.', []],
        ['Болит от холодной воды.', 'It hurts with cold water.', []],
        ['Я иду к стоматологу.', 'I go to the dentist.', []],
      ],
    },
    {
      title: 'Telling work you are ill',
      summary: 'Предупредить, что не выйдешь.',
      topics: [HE, 'a1-tema-work', 'a1-tema-contact'],
      dialogue: ['Звонок на работу', [
        ['Ben', 'Good morning. I am ill today.', 'Доброе утро. Я сегодня болею.'],
        ['Начальник', 'Sorry to hear that. What is wrong?', 'Сочувствую. Что случилось?'],
        ['Ben', 'Flu, I think. I have got a temperature.', 'Кажется, грипп. Температура.'],
        ['Начальник', 'Rest. We manage today.', 'Отдыхай. Сегодня справимся.'],
        ['Ben', 'Thank you. I write tomorrow.', 'Спасибо. Напишу завтра.'],
      ]],
      words: [
        ['I am ill.', 'Я болею.', 'I am ill today.'],
        ['Sorry to hear that.', 'Сочувствую.', 'Ill? Sorry to hear that.'],
        ['manage', 'справляться', 'We manage today.'],
        ['a sick day', 'больничный день', 'I take a sick day.'],
        ['tomorrow', 'завтра', 'I write tomorrow.'],
      ],
      rule: ['Ill и sick', 'В Британии ill — «болен», sick чаще значит «тошнит». В Америке sick — обычное «болен». Безопасно везде: I am not well today. А больничный называется sick leave в обеих странах.'],
      quiz: [
        ['«Я сегодня болею» (по-британски) —', ['I am ill today', 'I am sick today morning', 'I have ill today'], 0],
        ['«Сочувствую» —', ['Sorry to hear that', 'Sorry for hear that', 'Sorry that hear'], 0],
        ['«Мы справимся сегодня» —', ['We manage today', 'We are manage today', 'We manages today'], 0],
      ],
      order: ['Я сегодня болею.', 'I am ill today.'],
      produce: [
        ['Я сегодня болею.', 'I am ill today.', ["I'm ill today."]],
        ['Кажется, грипп.', 'Flu, I think.', []],
        ['Сочувствую.', 'Sorry to hear that.', []],
      ],
    },
    {
      title: 'Where is the hospital?',
      summary: 'Найти клинику или аптеку в чужом городе.',
      topics: [HE, CITY, Q],
      dialogue: ['Ищем аптеку', [
        ['Ben', 'Excuse me, is there a pharmacy near here?', 'Простите, здесь рядом есть аптека?'],
        ['Прохожая', 'Yes, opposite the hospital.', 'Да, напротив больницы.'],
        ['Ben', 'Is it open now?', 'Она сейчас открыта?'],
        ['Прохожая', 'Until ten, I think.', 'Кажется, до десяти.'],
        ['Ben', 'Thank you so much!', 'Огромное спасибо!'],
      ]],
      words: [
        ['a hospital', 'больница', 'Opposite the hospital.'],
        ['a clinic', 'клиника', 'A small clinic.'],
        ['open now', 'сейчас открыта', 'Is it open now?'],
        ['until ten', 'до десяти', 'Open until ten.'],
        ['near here', 'здесь рядом', 'A pharmacy near here.'],
      ],
      rule: ['In hospital и in the hospital', 'В Британии in hospital без артикля значит «лежит в больнице как пациент». In the hospital — просто находится в здании. Артикль здесь меняет смысл целиком, и это редкий, но заметный случай.'],
      quiz: [
        ['«Она сейчас открыта?» —', ['Is it open now?', 'Is it opened now?', 'It is open now?'], 0],
        ['«Напротив больницы» —', ['opposite the hospital', 'opposite of the hospital', 'in opposite hospital'], 0],
        ['«До десяти» —', ['until ten', 'to ten hours', 'till of ten'], 0],
      ],
      order: ['Здесь рядом есть аптека?', 'Is there a pharmacy near here?'],
      produce: [
        ['Здесь рядом есть аптека?', 'Is there a pharmacy near here?', []],
        ['Напротив больницы.', 'Opposite the hospital.', []],
        ['Она сейчас открыта?', 'Is it open now?', []],
      ],
    },
    {
      title: 'A visit to the doctor',
      summary: 'Весь блок одной сценой.',
      topics: [HE, HG, Q],
      dialogue: ['Приём целиком', [
        ['Врач', 'What is the problem?', 'Что беспокоит?'],
        ['Anna', 'I have got a headache and a temperature.', 'Голова болит и температура.'],
        ['Врач', 'Since when?', 'С каких пор?'],
        ['Anna', 'Since Monday. And I cannot sleep.', 'С понедельника. И не могу спать.'],
        ['Врач', 'Take these pills, two a day, and rest.', 'Принимайте эти таблетки, два раза в день, и отдыхайте.'],
      ]],
      words: [
        ['What is the problem?', 'Что беспокоит?', 'What is the problem today?'],
        ['I cannot sleep.', 'Я не могу спать.', 'I cannot sleep at night.'],
        ['these pills', 'эти таблетки', 'Take these pills.'],
        ['a prescription', 'рецепт', 'Here is your prescription.'],
        ['in three days', 'через три дня', 'Come back in three days.'],
      ],
      rule: ['Приём идёт по одной схеме', 'Что беспокоит → с каких пор → что ещё → назначение. Четыре шага, и на каждом от вас нужна одна короткая фраза. Зная схему, вы поймёте врача даже там, где половину слов не разобрали.'],
      quiz: [
        ['«Что беспокоит?» —', ['What is the problem?', 'What is problem?', 'Which is the problem it?'], 0],
        ['«Я не могу спать» —', ['I cannot sleep', 'I cannot to sleep', 'I do not can sleep'], 0],
        ['«Через три дня» —', ['in three days', 'through three days', 'after three days in'], 0],
      ],
      order: ['У меня болит голова и температура.', 'I have got a headache and a temperature.'],
      produce: [
        ['Что беспокоит?', 'What is the problem?', []],
        ['С понедельника.', 'Since Monday.', []],
        ['Я не могу спать.', 'I cannot sleep.', ["I can't sleep."]],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: здоровье',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [HE, HG, Q, C],
      produce: [
        ['У меня болит голова.', 'I have got a headache.', ['I have a headache.']],
        ['У меня болит спина.', 'My back hurts.', []],
        ['Что-нибудь от кашля, пожалуйста.', 'Something for a cough, please.', []],
        ['Мне нужно к врачу.', 'I need to see a doctor.', []],
        ['Тебе надо отдохнуть.', 'You should rest.', []],
        ['Вызовите скорую.', 'Call an ambulance.', []],
      ],
    },
  ],
}
