// Блок 17 — Hotel. Заселиться и решить вопрос на ресепшене.
//
// Отель — идеальная тренировка: разговор предсказуем от брони до выезда, а ошибиться
// не страшно. Здесь же собираются вместе have got, числа, время и просьбы — всё, что
// человек уже знает, но ещё не применял в одном диалоге подряд.

const T = 'a1-tema-travel'
const HG = 'a1-have-got'
const Q = 'a1-questions'
const C = 'a1-can'
const P = 'a1-tema-problems'
const D = 'a1-tema-description'
const SHOP = 'a1-tema-shopping'

export default {
  slug: 'hotel',
  title: 'Hotel',
  subtitle: 'Заселиться, попросить нужное и выехать без сюрпризов',
  canDo: [
    'заселиться по брони',
    'спросить про завтрак и вай-фай',
    'попросить полотенце или другой номер',
    'пожаловаться на шум или холод',
    'выехать и оплатить счёт',
  ],
  lessons: [
    {
      title: 'I have got a reservation',
      summary: 'Заселение по брони.',
      topics: [T, HG],
      dialogue: ['На ресепшене', [
        ['Ben', 'Good evening. I have got a reservation.', 'Добрый вечер. У меня бронь.'],
        ['Клерк', 'Your name, please?', 'Ваше имя?'],
        ['Ben', 'Ben Miller, two nights.', 'Бен Миллер, две ночи.'],
        ['Клерк', 'Yes, room two-oh-five. Your passport?', 'Да, номер двести пять. Ваш паспорт?'],
        ['Ben', 'Here you are.', 'Вот, пожалуйста.'],
      ]],
      words: [
        ['a reservation', 'бронь', 'I have got a reservation.'],
        ['two nights', 'две ночи', 'A room for two nights.'],
        ['check in', 'заселиться', 'I check in at three.'],
        ['a receptionist', 'администратор', 'Ask the receptionist.'],
        ['a passport', 'паспорт', 'Your passport, please.'],
      ],
      rule: ['Ночи, а не дни', 'Отель считает ночами: a room for two nights, не for two days. Так же спрашивают и в брони. Дни считают только в аренде машин и экскурсиях.'],
      quiz: [
        ['«Номер на две ночи» —', ['a room for two nights', 'a room for two days', 'a room on two nights'], 0],
        ['«У меня бронь» —', ['I have got a reservation', 'I have a reservation got', 'I am have reservation'], 0],
        ['«Заселиться» —', ['check in', 'check to in', 'in check'], 0],
      ],
      order: ['У меня бронь на две ночи.', 'I have got a reservation for two nights.'],
      produce: [
        ['У меня бронь.', 'I have got a reservation.', ['I have a reservation.']],
        ['Номер на две ночи.', 'A room for two nights.', []],
        ['Вот мой паспорт.', 'Here is my passport.', []],
      ],
    },
    {
      title: 'Is breakfast included?',
      summary: 'Что входит в цену.',
      topics: [T, Q, 'a1-tema-food'],
      dialogue: ['Что включено', [
        ['Anna', 'Is breakfast included?', 'Завтрак включён?'],
        ['Клерк', 'Yes, from seven to ten.', 'Да, с семи до десяти.'],
        ['Anna', 'And the wifi?', 'А вай-фай?'],
        ['Клерк', 'Free. The password is on the card.', 'Бесплатный. Пароль на карточке.'],
        ['Anna', 'Perfect, thank you.', 'Отлично, спасибо.'],
      ]],
      words: [
        ['included', 'включён', 'Is breakfast included?'],
        ['wifi', 'вай-фай', 'Is the wifi free?'],
        ['a password', 'пароль', 'The password is here.'],
        ['free', 'бесплатный', 'The wifi is free.'],
        ['a card', 'карточка', 'The password is on the card.'],
      ],
      rule: ['Три вопроса при заселении', 'Is breakfast included, is the wifi free, what time is check-out. Этих трёх хватает в любом отеле мира, и задают их именно в таком порядке. Всё остальное спрашивают уже по обстоятельствам.'],
      quiz: [
        ['«Завтрак включён?» —', ['Is breakfast included?', 'Is the breakfast include?', 'Breakfast is included it?'], 0],
        ['«Вай-фай бесплатный?» —', ['Is the wifi free?', 'Is wifi a free?', 'The wifi is free it?'], 0],
        ['«Пароль на карточке» —', ['The password is on the card', 'The password is in the card', 'The password on card is'], 0],
      ],
      order: ['Завтрак включён?', 'Is breakfast included?'],
      produce: [
        ['Завтрак включён?', 'Is breakfast included?', []],
        ['Вай-фай бесплатный?', 'Is the wifi free?', []],
        ['Пароль на карточке.', 'The password is on the card.', []],
      ],
    },
    {
      title: 'What time is check-out?',
      summary: 'Время выезда и хранение багажа.',
      topics: [T, Q, 'a1-prepositions-time'],
      dialogue: ['Про выезд', [
        ['Ben', 'What time is check-out?', 'Во сколько выезд?'],
        ['Клерк', 'Eleven o\'clock.', 'В одиннадцать.'],
        ['Ben', 'Can I leave my bags here after?', 'Можно оставить сумки после?'],
        ['Клерк', 'Of course, until six.', 'Конечно, до шести.'],
        ['Ben', 'That helps a lot, thank you.', 'Это очень помогает, спасибо.'],
      ]],
      words: [
        ['check-out', 'выезд', 'Check-out is at eleven.'],
        ['leave', 'оставить', 'Can I leave my bags?'],
        ['bags', 'сумки, багаж', 'My bags are heavy.'],
        ['until six', 'до шести', 'Until six, no problem.'],
        ['luggage', 'багаж', 'Where is the luggage room?'],
      ],
      rule: ['Luggage не считают', 'Luggage — багаж вообще, без множественного и без артикля: my luggage is heavy. Считают места: two bags, three suitcases. Так же ведут себя information и furniture.'],
      quiz: [
        ['«Мой багаж тяжёлый» —', ['My luggage is heavy', 'My luggages are heavy', 'My luggage are heavy'], 0],
        ['«Во сколько выезд?» —', ['What time is check-out?', 'What time check-out is?', 'Which time is check out?'], 0],
        ['«Можно оставить сумки?» —', ['Can I leave my bags?', 'Can I leave my bags to?', 'Can I to leave my bags?'], 0],
      ],
      order: ['Во сколько выезд?', 'What time is check-out?'],
      produce: [
        ['Во сколько выезд?', 'What time is check-out?', []],
        ['Можно оставить сумки здесь?', 'Can I leave my bags here?', []],
        ['Мой багаж тяжёлый.', 'My luggage is heavy.', []],
      ],
    },
    {
      title: 'Can I have a towel?',
      summary: 'Попросить то, чего не хватает.',
      topics: [T, C],
      dialogue: ['Просьба в номер', [
        ['Anna', 'Can I have another towel, please?', 'Можно ещё одно полотенце?'],
        ['Клерк', 'Of course. Room number?', 'Конечно. Номер комнаты?'],
        ['Anna', 'Three-one-four.', 'Триста четырнадцать.'],
        ['Клерк', 'In ten minutes.', 'Через десять минут.'],
        ['Anna', 'Thank you very much.', 'Большое спасибо.'],
      ]],
      words: [
        ['a towel', 'полотенце', 'Another towel, please.'],
        ['another', 'ещё один', 'Another towel.'],
        ['soap', 'мыло', 'There is no soap.'],
        ['a pillow', 'подушка', 'One more pillow, please.'],
        ['a blanket', 'одеяло', 'A warm blanket.'],
      ],
      rule: ['Another и one more', 'Another towel — ещё одно, дополнительное. One more towel — то же самое, чуть разговорнее. А the other towel — «другое, второе из двух», и это уже совсем иной смысл.'],
      quiz: [
        ['«Ещё одно полотенце» —', ['another towel', 'other towel', 'an other towel'], 0],
        ['«Ещё одну подушку» —', ['one more pillow', 'more one pillow', 'one pillow more it'], 0],
        ['«Мыла нет» —', ['There is no soap', 'There is not a soap', 'It has no soap there'], 0],
      ],
      order: ['Можно ещё одно полотенце?', 'Can I have another towel?'],
      produce: [
        ['Можно ещё одно полотенце?', 'Can I have another towel?', []],
        ['Мыла нет.', 'There is no soap.', []],
        ['Ещё одну подушку, пожалуйста.', 'One more pillow, please.', []],
      ],
    },
    {
      title: 'The room is too noisy',
      summary: 'Пожаловаться и попросить другой номер.',
      topics: [T, P, D],
      dialogue: ['Шумно', [
        ['Ben', 'The room is very noisy.', 'В номере очень шумно.'],
        ['Клерк', 'I am sorry. Which room?', 'Извините. Какой номер?'],
        ['Ben', 'Two-oh-five, next to the street.', 'Двести пять, у улицы.'],
        ['Клерк', 'I can change it. Room four-one-one is quiet.', 'Могу поменять. Четыреста одиннадцать тихий.'],
        ['Ben', 'That would be great.', 'Это было бы отлично.'],
      ]],
      words: [
        ['noisy', 'шумный', 'The room is noisy.'],
        ['change', 'поменять', 'I can change it.'],
        ['quiet', 'тихий', 'A quiet room.'],
        ['next to the street', 'у улицы', 'A room next to the street.'],
        ['That would be great.', 'Это было бы отлично.', 'A quiet room? That would be great.'],
      ],
      rule: ['Жалоба через факт, а не через обвинение', 'The room is noisy — констатация, на которую легко отвечать. You gave me a bad room — обвинение, после которого разговор портится. Английский в сфере услуг устроен на первом варианте.'],
      quiz: [
        ['«В номере шумно» —', ['The room is noisy', 'The room is noise', 'In the room is noisy'], 0],
        ['«Могу поменять» —', ['I can change it', 'I can to change it', 'I can changing it'], 0],
        ['«Это было бы отлично» —', ['That would be great', 'That will be great would', 'It would to be great'], 0],
      ],
      order: ['В номере очень шумно.', 'The room is very noisy.'],
      produce: [
        ['В номере шумно.', 'The room is noisy.', []],
        ['Можно поменять номер?', 'Can I change the room?', []],
        ['Тихий номер, пожалуйста.', 'A quiet room, please.', []],
      ],
    },
    {
      title: 'The key does not work',
      summary: 'Технические неполадки в номере.',
      topics: [T, P],
      dialogue: ['Не открывается', [
        ['Anna', 'My key does not work.', 'Мой ключ не работает.'],
        ['Клерк', 'Let me check. Room?', 'Дайте проверю. Номер?'],
        ['Anna', 'Three-one-four.', 'Триста четырнадцать.'],
        ['Клерк', 'Here is a new card. Try again.', 'Вот новая карта. Попробуйте ещё раз.'],
        ['Anna', 'It works now, thank you!', 'Теперь работает, спасибо!'],
      ]],
      words: [
        ['a key card', 'ключ-карта', 'The key card does not work.'],
        ['Let me check.', 'Дайте проверю.', 'Let me check for you.'],
        ['try again', 'попробовать ещё раз', 'Try again, please.'],
        ['It works.', 'Работает.', 'It works now.'],
        ['the air conditioning', 'кондиционер', 'The air conditioning is off.'],
      ],
      rule: ['Let me — «дайте я»', 'Let me check, let me see, let me help — вежливое предложение сделать что-то самому. После let me глагол без to. Это одна из самых частых фраз в сфере услуг.'],
      quiz: [
        ['«Дайте проверю» —', ['Let me check', 'Let me to check', 'Let me checking'], 0],
        ['«Ключ не работает» —', ['The key does not work', 'The key do not work', 'The key does not works'], 0],
        ['«Попробуйте ещё раз» —', ['Try again', 'Try one more again', 'Try it again more'], 0],
      ],
      order: ['Мой ключ не работает.', 'My key does not work.'],
      produce: [
        ['Мой ключ не работает.', 'My key does not work.', ["My key doesn't work."]],
        ['Дайте проверю.', 'Let me check.', []],
        ['Теперь работает.', 'It works now.', []],
      ],
    },
    {
      title: 'Where is the lift?',
      summary: 'Ориентироваться в отеле.',
      topics: [T, Q, 'a1-tema-city'],
      dialogue: ['По зданию', [
        ['Ben', 'Where is the lift?', 'Где лифт?'],
        ['Клерк', 'Behind you, on the right.', 'За вами, справа.'],
        ['Ben', 'And the restaurant?', 'А ресторан?'],
        ['Клерк', 'On the ground floor.', 'На первом этаже.'],
        ['Ben', 'Thank you.', 'Спасибо.'],
      ]],
      words: [
        ['a lift', 'лифт', 'Where is the lift?'],
        ['the ground floor', 'первый этаж', 'On the ground floor.'],
        ['stairs', 'лестница', 'Take the stairs.'],
        ['a restaurant', 'ресторан', 'The hotel restaurant.'],
        ['a gym', 'спортзал', 'Is there a gym?'],
      ],
      rule: ['Lift и elevator', 'В Британии lift, в Америке elevator. Ground floor и first floor — тоже британские: первый этаж по-нашему это ground floor, а first floor уже второй. В американском отеле first floor — на уровне улицы.'],
      quiz: [
        ['Лифт по-британски —', ['a lift', 'an elevator', 'a raiser'], 0],
        ['Первый этаж (по-британски) —', ['the ground floor', 'the first floor', 'the zero floor'], 0],
        ['«Идите по лестнице» —', ['Take the stairs', 'Go by stairs the', 'Take stairs on'], 0],
      ],
      order: ['Ресторан на первом этаже.', 'The restaurant is on the ground floor.'],
      produce: [
        ['Где лифт?', 'Where is the lift?', []],
        ['На первом этаже.', 'On the ground floor.', []],
        ['Спортзал есть?', 'Is there a gym?', []],
      ],
    },
    {
      title: 'A room with a view',
      summary: 'Какие бывают номера.',
      topics: [T, D, SHOP],
      dialogue: ['Выбор номера', [
        ['Anna', 'Do you have a room with a view?', 'Есть номер с видом?'],
        ['Клерк', 'Yes, but it is thirty pounds more.', 'Да, но на тридцать фунтов дороже.'],
        ['Anna', 'Is it much quieter?', 'Он намного тише?'],
        ['Клерк', 'Much quieter, it is at the back.', 'Гораздо тише, он с обратной стороны.'],
        ['Anna', 'Then yes, please.', 'Тогда да, пожалуйста.'],
      ]],
      words: [
        ['a view', 'вид', 'A room with a view.'],
        ['a double room', 'двухместный номер', 'A double room, please.'],
        ['a single room', 'одноместный номер', 'A single room for one night.'],
        ['much quieter', 'намного тише', 'Much quieter at the back.'],
        ['thirty pounds more', 'на тридцать фунтов дороже', 'It is thirty pounds more.'],
      ],
      rule: ['Much перед сравнением', 'Much quieter, much better, much more expensive — much усиливает сравнительную форму. Very с ней не работает: very quieter — ошибка. Запомнить проще парой: very quiet, но much quieter.'],
      quiz: [
        ['«Намного тише» —', ['much quieter', 'very quieter', 'more quieter'], 0],
        ['«Номер с видом» —', ['a room with a view', 'a room with view', 'a room of a view'], 0],
        ['«На тридцать фунтов дороже» —', ['thirty pounds more', 'more thirty pounds', 'on thirty pounds more'], 0],
      ],
      order: ['Есть номер с видом?', 'Do you have a room with a view?'],
      produce: [
        ['Есть номер с видом?', 'Do you have a room with a view?', []],
        ['Он намного тише.', 'It is much quieter.', ["It's much quieter."]],
        ['Одноместный номер на одну ночь.', 'A single room for one night.', []],
      ],
    },
    {
      title: 'Booking by phone',
      summary: 'Забронировать номер заранее.',
      topics: [T, 'a1-tema-contact', Q],
      dialogue: ['Звонок в отель', [
        ['Ben', 'I would like to book a room, please.', 'Я хотел бы забронировать номер.'],
        ['Отель', 'For which dates?', 'На какие даты?'],
        ['Ben', 'From the fifth to the seventh of June.', 'С пятого по седьмое июня.'],
        ['Отель', 'A single or a double?', 'Одноместный или двухместный?'],
        ['Ben', 'A double, please. And my name is Miller.', 'Двухместный. Моя фамилия Миллер.'],
      ]],
      words: [
        ['book a room', 'забронировать номер', 'I would like to book a room.'],
        ['dates', 'даты', 'For which dates?'],
        ['from the fifth to the seventh', 'с пятого по седьмое', 'From the fifth to the seventh.'],
        ['June', 'июнь', 'In June.'],
        ['a confirmation', 'подтверждение', 'A confirmation by email.'],
      ],
      rule: ['Даты: the fifth of June', 'Британцы говорят the fifth of June, американцы June fifth. Артикль the и предлог of обязательны в британском варианте, и именно его вы услышите в европейском отеле.'],
      quiz: [
        ['«Пятое июня» (по-британски) —', ['the fifth of June', 'June the fifth of', 'fifth June the'], 0],
        ['«На какие даты?» —', ['For which dates?', 'On which dates?', 'For what dates it?'], 0],
        ['«Подтверждение по почте» —', ['a confirmation by email', 'a confirm on email', 'a confirmation of email'], 0],
      ],
      order: ['С пятого по седьмое июня.', 'From the fifth to the seventh of June.'],
      produce: [
        ['Я хотел бы забронировать номер.', 'I would like to book a room.', ["I'd like to book a room."]],
        ['С пятого по седьмое июня.', 'From the fifth to the seventh of June.', []],
        ['Двухместный, пожалуйста.', 'A double, please.', []],
      ],
    },
    {
      title: 'Paying the bill',
      summary: 'Выезд и оплата.',
      topics: [T, SHOP],
      dialogue: ['Выезжаем', [
        ['Ben', 'I am checking out, room two-oh-five.', 'Выезжаю, номер двести пять.'],
        ['Клерк', 'One moment. Here is your bill.', 'Минуту. Вот ваш счёт.'],
        ['Ben', 'What is this line?', 'А что это за строка?'],
        ['Клерк', 'The minibar, two waters.', 'Мини-бар, две воды.'],
        ['Ben', 'Ah, yes. Card, please.', 'А, да. Картой.'],
      ]],
      words: [
        ['check out', 'выехать', 'I am checking out.'],
        ['a bill', 'счёт', 'Here is your bill.'],
        ['a line', 'строка', 'What is this line?'],
        ['a minibar', 'мини-бар', 'The minibar is expensive.'],
        ['a receipt', 'чек', 'Can I have a receipt?'],
      ],
      rule: ['Check in и check out — раздельно', 'Как глаголы они пишутся в два слова: I check in, I am checking out. Как существительные — через дефис: check-in is at three, check-out is at eleven. Мелочь для письма, но заметная.'],
      quiz: [
        ['«Я выезжаю» —', ['I am checking out', 'I am check out', 'I checking out'], 0],
        ['«Вот ваш счёт» —', ['Here is your bill', 'Here your bill is', 'Here is the your bill'], 0],
        ['«Можно чек?» —', ['Can I have a receipt?', 'Can I get the receipt one?', 'Can I to have receipt?'], 0],
      ],
      order: ['Выезжаю, номер двести пять.', 'I am checking out, room two-oh-five.'],
      produce: [
        ['Я выезжаю.', 'I am checking out.', ["I'm checking out."]],
        ['Что это за строка?', 'What is this line?', []],
        ['Можно чек?', 'Can I have a receipt?', []],
      ],
    },
    {
      title: 'Asking for recommendations',
      summary: 'Спросить совета у администратора.',
      topics: [T, Q, 'a1-tema-food'],
      dialogue: ['Что посоветуете', [
        ['Anna', 'Can you recommend a restaurant?', 'Посоветуете ресторан?'],
        ['Клерк', 'Italian or local food?', 'Итальянский или местная кухня?'],
        ['Anna', 'Local, please. Not expensive.', 'Местная. Недорого.'],
        ['Клерк', 'Then this one, five minutes on foot.', 'Тогда вот этот, пять минут пешком.'],
        ['Anna', 'Great, thank you!', 'Отлично, спасибо!'],
      ]],
      words: [
        ['recommend', 'посоветовать', 'Can you recommend a restaurant?'],
        ['local food', 'местная кухня', 'I like local food.'],
        ['not expensive', 'недорого', 'Good and not expensive.'],
        ['this one', 'вот этот', 'Then this one.'],
        ['a recommendation', 'рекомендация', 'Thanks for the recommendation.'],
      ],
      rule: ['Recommend без предлога', 'Can you recommend a restaurant — без to и без for. А вот совет кому-то — recommend it to me. Ошибка recommend me a restaurant очень распространена и звучит неправильно, хотя вас поймут.'],
      quiz: [
        ['«Посоветуете ресторан?» —', ['Can you recommend a restaurant?', 'Can you recommend me a restaurant?', 'Can you to recommend restaurant?'], 0],
        ['«Местная кухня» —', ['local food', 'the local of food', 'food local'], 0],
        ['«Недорого» —', ['not expensive', 'no expensive', 'not a expensive'], 0],
      ],
      order: ['Посоветуете ресторан?', 'Can you recommend a restaurant?'],
      produce: [
        ['Посоветуете ресторан?', 'Can you recommend a restaurant?', []],
        ['Местная кухня, недорого.', 'Local food, not expensive.', []],
        ['Пять минут пешком.', 'Five minutes on foot.', []],
      ],
    },
    {
      title: 'Wake-up call and taxi',
      summary: 'Договориться о раннем утре.',
      topics: [T, 'a1-tema-contact', C],
      dialogue: ['Ранний вылет', [
        ['Ben', 'Can I have a wake-up call at five?', 'Можно разбудить меня в пять?'],
        ['Клерк', 'Of course. And a taxi?', 'Конечно. И такси?'],
        ['Ben', 'Yes, at half past five, to the airport.', 'Да, в полшестого, в аэропорт.'],
        ['Клерк', 'It is booked.', 'Заказано.'],
        ['Ben', 'Thank you. Good night.', 'Спасибо. Спокойной ночи.'],
      ]],
      words: [
        ['a wake-up call', 'звонок-будильник', 'A wake-up call at five.'],
        ['an airport', 'аэропорт', 'To the airport, please.'],
        ['It is booked.', 'Заказано.', 'The taxi is booked.'],
        ['early', 'ранний', 'An early flight.'],
        ['a flight', 'рейс', 'My flight is at seven.'],
      ],
      rule: ['To the airport', 'Направление — всегда с to: to the airport, to the station, to the centre. Исключение только home: go home, без предлога. Это исключение одно из немногих, но встречается постоянно.'],
      quiz: [
        ['«В аэропорт» —', ['to the airport', 'in the airport', 'at airport'], 0],
        ['«Иду домой» —', ['I go home', 'I go to home', 'I go at home'], 0],
        ['«Заказано» —', ['It is booked', 'It is book', 'It has booked'], 0],
      ],
      order: ['Такси в аэропорт, в полшестого.', 'A taxi to the airport, at half past five.'],
      produce: [
        ['Можно разбудить меня в пять?', 'Can I have a wake-up call at five?', []],
        ['Такси в аэропорт.', 'A taxi to the airport.', []],
        ['Мой рейс в семь.', 'My flight is at seven.', []],
      ],
    },
    {
      title: 'Hostel and apartment',
      summary: 'Другие виды жилья.',
      topics: [T, D, SHOP],
      dialogue: ['Не отель', [
        ['Anna', 'Is it a hotel or a hostel?', 'Это отель или хостел?'],
        ['Ben', 'A hostel, but with private rooms.', 'Хостел, но с отдельными комнатами.'],
        ['Anna', 'Shared bathroom?', 'Ванная общая?'],
        ['Ben', 'Yes, but it is clean.', 'Да, но чисто.'],
        ['Anna', 'And half the price.', 'И вдвое дешевле.'],
      ]],
      words: [
        ['a hostel', 'хостел', 'A cheap hostel.'],
        ['private', 'отдельный, частный', 'A private room.'],
        ['shared', 'общий', 'A shared bathroom.'],
        ['clean', 'чистый', 'It is clean.'],
        ['half the price', 'вдвое дешевле', 'And half the price.'],
      ],
      rule: ['Half the price', 'Дословно «половина цены» — так и говорят: half the price, half the time, half the people. Артикль стоит после half, и это единственное место в языке, где такой порядок нормален.'],
      quiz: [
        ['«Вдвое дешевле» —', ['half the price', 'the half price', 'a half of price'], 0],
        ['«Общая ванная» —', ['a shared bathroom', 'a share bathroom', 'a common of bathroom'], 0],
        ['«Отдельная комната» —', ['a private room', 'a privat room', 'an own private room'], 0],
      ],
      order: ['Хостел, но с отдельными комнатами.', 'A hostel, but with private rooms.'],
      produce: [
        ['Это отель или хостел?', 'Is it a hotel or a hostel?', []],
        ['Ванная общая.', 'The bathroom is shared.', []],
        ['И вдвое дешевле.', 'And half the price.', []],
      ],
    },
    {
      title: 'Lost something',
      summary: 'Забыл вещь в номере.',
      topics: [T, P, Q],
      dialogue: ['Забыл зарядку', [
        ['Ben', 'I think I left my charger in the room.', 'Кажется, я забыл зарядку в номере.'],
        ['Клерк', 'Which room?', 'Какой номер?'],
        ['Ben', 'Two-oh-five, I checked out this morning.', 'Двести пять, выехал утром.'],
        ['Клерк', 'One moment, I ask housekeeping.', 'Минуту, спрошу горничных.'],
        ['Ben', 'Thank you so much.', 'Огромное спасибо.'],
      ]],
      words: [
        ['I left', 'я забыл, оставил', 'I left my charger.'],
        ['a charger', 'зарядка', 'My phone charger.'],
        ['housekeeping', 'горничные, уборка', 'I ask housekeeping.'],
        ['lost property', 'бюро находок', 'Ask at lost property.'],
        ['this morning', 'сегодня утром', 'I checked out this morning.'],
      ],
      rule: ['Leave и forget', 'Leave — оставить где-то: I left my charger in the room. Forget — забыть вообще, без места: I forgot my charger. С указанием места по-английски говорят именно leave, и это отличается от русского «забыл в номере».'],
      quiz: [
        ['«Я забыл зарядку в номере» —', ['I left my charger in the room', 'I forgot my charger in the room', 'I forget the charger in room'], 0],
        ['«Бюро находок» —', ['lost property', 'the lost things office', 'found property'], 0],
        ['«Сегодня утром» —', ['this morning', 'in this morning', 'at this morning'], 0],
      ],
      order: ['Кажется, я забыл зарядку в номере.', 'I think I left my charger in the room.'],
      produce: [
        ['Я забыл зарядку в номере.', 'I left my charger in the room.', []],
        ['Я выехал сегодня утром.', 'I checked out this morning.', []],
        ['Огромное спасибо.', 'Thank you so much.', []],
      ],
    },
    {
      title: 'Was everything OK?',
      summary: 'Отзыв при выезде.',
      topics: [T, D, 'a1-tema-greetings'],
      dialogue: ['Обратная связь', [
        ['Клерк', 'Was everything OK?', 'Всё было хорошо?'],
        ['Anna', 'Yes, very comfortable. Thank you.', 'Да, очень удобно. Спасибо.'],
        ['Клерк', 'And the breakfast?', 'А завтрак?'],
        ['Anna', 'Excellent, honestly.', 'Отличный, честно.'],
        ['Клерк', 'We are glad. Come back soon!', 'Мы рады. Приезжайте ещё!'],
      ]],
      words: [
        ['Was everything OK?', 'Всё было хорошо?', 'Was everything OK with the room?'],
        ['comfortable', 'удобный', 'A comfortable bed.'],
        ['excellent', 'отличный', 'The breakfast was excellent.'],
        ['We are glad.', 'Мы рады.', 'We are glad you liked it.'],
        ['Come back soon.', 'Приезжайте ещё.', 'Come back soon!'],
      ],
      rule: ['Was — прошедшее от is', 'Was everything OK, it was comfortable, the breakfast was excellent. Was и were — единственное прошедшее, которое нужно на A1, и встречается оно чаще всего именно в отзывах и рассказах о поездке.'],
      quiz: [
        ['«Всё было хорошо?» —', ['Was everything OK?', 'Were everything OK?', 'Was everything is OK?'], 0],
        ['«Завтрак был отличный» —', ['The breakfast was excellent', 'The breakfast were excellent', 'The breakfast is was excellent'], 0],
        ['«Кровать была удобная» —', ['The bed was comfortable', 'The bed were comfortable', 'The bed was comfortably'], 0],
      ],
      order: ['Завтрак был отличный.', 'The breakfast was excellent.'],
      produce: [
        ['Всё было хорошо?', 'Was everything OK?', []],
        ['Было очень удобно.', 'It was very comfortable.', []],
        ['Приезжайте ещё!', 'Come back soon!', []],
      ],
    },
    {
      title: 'Two nights, start to finish',
      summary: 'Весь блок: от брони до выезда.',
      topics: [T, HG, C],
      dialogue: ['Две ночи целиком', [
        ['Ben', 'Good evening. I have got a reservation, Miller.', 'Добрый вечер. У меня бронь, Миллер.'],
        ['Клерк', 'Two nights, room two-oh-five. Breakfast is included.', 'Две ночи, номер двести пять. Завтрак включён.'],
        ['Ben', 'What time is check-out?', 'Во сколько выезд?'],
        ['Клерк', 'Eleven. And here is the wifi password.', 'В одиннадцать. Вот пароль от вай-фая.'],
        ['Ben', 'Perfect. Thank you very much.', 'Отлично. Большое спасибо.'],
      ]],
      words: [
        ['Enjoy your stay.', 'Приятного пребывания.', 'Room two-oh-five. Enjoy your stay!'],
        ['a stay', 'пребывание', 'A short stay.'],
        ['a floor plan', 'план этажа', 'The floor plan is on the door.'],
        ['an emergency exit', 'запасной выход', 'The emergency exit is there.'],
        ['quiet hours', 'тихие часы', 'Quiet hours after eleven.'],
      ],
      rule: ['Заселение — четыре реплики', 'Бронь → номер и что включено → выезд и вай-фай → спасибо. Дальше вы уже в номере. Отель хорош для тренировки именно предсказуемостью: одни и те же четыре реплики в любой стране.'],
      quiz: [
        ['«Приятного пребывания» —', ['Enjoy your stay', 'Enjoy of your stay', 'Have a enjoy stay'], 0],
        ['«Запасной выход» —', ['an emergency exit', 'an emergency of exit', 'a reserve exit'], 0],
        ['«Пароль от вай-фая» —', ['the wifi password', 'the password of wifi one', 'the wifi of password'], 0],
      ],
      order: ['Вот пароль от вай-фая.', 'Here is the wifi password.'],
      produce: [
        ['У меня бронь, Миллер.', 'I have got a reservation, Miller.', ['I have a reservation, Miller.']],
        ['Во сколько выезд?', 'What time is check-out?', []],
        ['Приятного пребывания!', 'Enjoy your stay!', []],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: отель',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [T, HG, C, P],
      produce: [
        ['У меня бронь на две ночи.', 'I have got a reservation for two nights.', ['I have a reservation for two nights.']],
        ['Завтрак включён?', 'Is breakfast included?', []],
        ['Во сколько выезд?', 'What time is check-out?', []],
        ['Можно ещё одно полотенце?', 'Can I have another towel?', []],
        ['В номере шумно.', 'The room is noisy.', []],
        ['Посоветуете ресторан?', 'Can you recommend a restaurant?', []],
      ],
    },
  ],
}
