// Блок 19 — Work. Назвать профессию и рассказать про свой день.
//
// Тут наконец берётся третье лицо целиком: he works, she does not work, does he work.
// Тема выбрана потому, что о работе всегда говорят про кого-то ещё — про коллегу,
// начальника, компанию, — и окончание -s всплывает в каждой второй фразе.

const W = 'a1-tema-work'
const PS = 'a1-present-simple'
const Q = 'a1-questions'
const CON = 'a1-tema-contact'
const M = 'a1-tema-meetings'
const D = 'a1-tema-description'
const C = 'a1-can'

export default {
  slug: 'work',
  title: 'Work',
  subtitle: 'Третье лицо: он работает, она не работает, работает ли он',
  canDo: [
    'назвать профессию свою и чужую',
    'рассказать, чем занимается коллега',
    'спросить о чужой работе',
    'описать рабочий день и обязанности',
    'сказать, что тебе нравится в работе',
  ],
  lessons: [
    {
      title: 'He works in an office',
      summary: 'Окончание -s в третьем лице.',
      topics: [PS, W],
      dialogue: ['О коллеге', [
        ['Anna', 'What does your brother do?', 'Чем занимается твой брат?'],
        ['Ben', 'He works in an office.', 'Он работает в офисе.'],
        ['Anna', 'In which company?', 'В какой компании?'],
        ['Ben', 'A small one, near the station.', 'В небольшой, у вокзала.'],
        ['Anna', 'And he likes it?', 'И ему нравится?'],
      ]],
      words: [
        ['he works', 'он работает', 'He works in an office.'],
        ['she lives', 'она живёт', 'She lives in London.'],
        ['he likes', 'ему нравится', 'He likes his job.'],
        ['a job', 'работа (место)', 'A good job.'],
        ['a company', 'компания', 'A small company.'],
      ],
      rule: ['-s только с he, she, it', 'I work, you work, we work, they work — но he works, she works, it works. Одно окончание на одно лицо, и его теряют годами. Проверка простая: если подлежащее можно заменить на he или she — нужна -s.'],
      quiz: [
        ['«Он работает в офисе» —', ['He works in an office', 'He work in an office', 'He is work in an office'], 0],
        ['«Ему нравится работа» —', ['He likes his job', 'He like his job', 'He likes his work job'], 0],
        ['«Они работают здесь» —', ['They work here', 'They works here', 'They are work here'], 0],
      ],
      order: ['Он работает в офисе.', 'He works in an office.'],
      produce: [
        ['Он работает в офисе.', 'He works in an office.', []],
        ['Она живёт в Лондоне.', 'She lives in London.', []],
        ['Ему нравится его работа.', 'He likes his job.', []],
      ],
    },
    {
      title: 'Does he work here?',
      summary: 'Вопрос в третьем лице.',
      topics: [PS, Q, W],
      dialogue: ['Ищу человека', [
        ['Anna', 'Does Mr Brown work here?', 'Мистер Браун здесь работает?'],
        ['Секретарь', 'Yes, he does. Third floor.', 'Да. Третий этаж.'],
        ['Anna', 'Does he start early?', 'Он рано начинает?'],
        ['Секретарь', 'He usually comes at eight.', 'Обычно приходит в восемь.'],
        ['Anna', 'Thank you, I wait.', 'Спасибо, подожду.'],
      ]],
      words: [
        ['Does he…?', 'Он …?', 'Does he work here?'],
        ['Yes, he does.', 'Да.', 'Does he work here? — Yes, he does.'],
        ['he comes', 'он приходит', 'He comes at eight.'],
        ['start', 'начинать', 'He starts early.'],
        ['wait', 'ждать', 'I wait here.'],
      ],
      rule: ['Does забирает -s себе', 'Does he work — не does he works. Окончание уходит во вспомогательный глагол, и основной остаётся чистым. Та же логика в отрицании: he does not work. Это правило нарушают чаще любого другого.'],
      quiz: [
        ['«Он здесь работает?» —', ['Does he work here?', 'Does he works here?', 'Do he work here?'], 0],
        ['Короткий ответ:', ['Yes, he does', 'Yes, he do', 'Yes, he works does'], 0],
        ['«Он рано начинает?» —', ['Does he start early?', 'Does he starts early?', 'Do he starts early?'], 0],
      ],
      order: ['Мистер Браун здесь работает?', 'Does Mr Brown work here?'],
      produce: [
        ['Он здесь работает?', 'Does he work here?', []],
        ['Да, работает.', 'Yes, he does.', []],
        ['Он приходит в восемь.', 'He comes at eight.', []],
      ],
    },
    {
      title: 'She does not work on Fridays',
      summary: 'Отрицание в третьем лице.',
      topics: [PS, W],
      dialogue: ['Не в этот день', [
        ['Ben', 'Is Maria in the office?', 'Мария в офисе?'],
        ['Anna', 'She does not work on Fridays.', 'Она по пятницам не работает.'],
        ['Ben', 'And on Monday?', 'А в понедельник?'],
        ['Anna', 'Yes, from nine.', 'Да, с девяти.'],
        ['Ben', 'Then I write to her.', 'Тогда напишу ей.'],
      ]],
      words: [
        ['does not work', 'не работает', 'She does not work on Fridays.'],
        ['on Fridays', 'по пятницам', 'She is free on Fridays.'],
        ['from nine', 'с девяти', 'She works from nine.'],
        ['write to her', 'написать ей', 'I write to her today.'],
        ['in the office', 'в офисе', 'Is Maria in the office?'],
      ],
      rule: ['Doesn\'t в речи', 'She does not work сокращают до she doesn\'t work. Полная форма звучит подчёркнуто, как возражение. В переписке пишут и так и так, но вслух почти всегда сокращают.'],
      quiz: [
        ['«Она не работает по пятницам» —', ['She does not work on Fridays', 'She do not work on Fridays', 'She does not works on Friday'], 0],
        ['Сокращение does not —', ["doesn't", "don't", "does'nt"], 0],
        ['«Я напишу ей» —', ['I write to her', 'I write her to', 'I write at her'], 0],
      ],
      order: ['Она по пятницам не работает.', 'She does not work on Fridays.'],
      produce: [
        ['Она не работает по пятницам.', 'She does not work on Fridays.', ["She doesn't work on Fridays."]],
        ['Она работает с девяти.', 'She works from nine.', []],
        ['Тогда напишу ей.', 'Then I write to her.', []],
      ],
    },
    {
      title: 'Jobs',
      summary: 'Двадцать профессий, которых хватает.',
      topics: [W, D],
      dialogue: ['Кто кем', [
        ['Anna', 'My sister is a nurse.', 'Моя сестра медсестра.'],
        ['Ben', 'In a hospital?', 'В больнице?'],
        ['Anna', 'Yes. And my father is a driver.', 'Да. А папа водитель.'],
        ['Ben', 'My mother is a shop assistant.', 'Моя мама продавец.'],
        ['Anna', 'Hard work, both.', 'Обе работы тяжёлые.'],
      ]],
      words: [
        ['a nurse', 'медсестра', 'She is a nurse.'],
        ['a driver', 'водитель', 'My father is a driver.'],
        ['a shop assistant', 'продавец', 'A shop assistant in a supermarket.'],
        ['a cook', 'повар', 'He is a cook.'],
        ['a builder', 'строитель', 'A builder works outside.'],
      ],
      rule: ['Артикль перед профессией', 'She is a nurse, he is a driver — артикль обязателен. Без него получается заголовок или подпись под фотографией. Множественное — без артикля: they are nurses.'],
      quiz: [
        ['«Она медсестра» —', ['She is a nurse', 'She is nurse', 'She is the nurse'], 0],
        ['«Они водители» —', ['They are drivers', 'They are a drivers', 'They is drivers'], 0],
        ['«Он повар» —', ['He is a cook', 'He is cook', 'He is a cooker'], 0],
      ],
      order: ['Мой папа водитель.', 'My father is a driver.'],
      produce: [
        ['Моя сестра медсестра.', 'My sister is a nurse.', []],
        ['Он повар.', 'He is a cook.', []],
        ['Они водители.', 'They are drivers.', []],
      ],
    },
    {
      title: 'What does your job involve?',
      summary: 'Рассказать про обязанности.',
      topics: [W, PS, Q],
      dialogue: ['Чем именно занимаешься', [
        ['Anna', 'What do you do exactly?', 'А чем именно занимаешься?'],
        ['Ben', 'I answer emails and talk to clients.', 'Отвечаю на письма и общаюсь с клиентами.'],
        ['Anna', 'Every day?', 'Каждый день?'],
        ['Ben', 'Mostly. And I write reports.', 'В основном. И пишу отчёты.'],
        ['Anna', 'Sounds busy.', 'Звучит хлопотно.'],
      ]],
      words: [
        ['answer emails', 'отвечать на письма', 'I answer emails all day.'],
        ['talk to clients', 'общаться с клиентами', 'I talk to clients.'],
        ['write reports', 'писать отчёты', 'I write reports on Fridays.'],
        ['mostly', 'в основном', 'Mostly, yes.'],
        ['exactly', 'именно', 'What do you do exactly?'],
      ],
      rule: ['Talk to и speak with', 'Talk to clients, speak to the manager — обычные варианты. Speak with чаще в Америке. А вот talk with почти не говорят: если сомневаетесь, ставьте to.'],
      quiz: [
        ['«Общаюсь с клиентами» —', ['I talk to clients', 'I talk with clients about', 'I speak clients'], 0],
        ['«Отвечаю на письма» —', ['I answer emails', 'I answer to emails', 'I respond emails on'], 0],
        ['«В основном» —', ['mostly', 'most of', 'mainly mostly'], 0],
      ],
      order: ['Отвечаю на письма и общаюсь с клиентами.', 'I answer emails and talk to clients.'],
      produce: [
        ['Я отвечаю на письма.', 'I answer emails.', []],
        ['Я пишу отчёты.', 'I write reports.', []],
        ['Чем именно занимаешься?', 'What do you do exactly?', []],
      ],
    },
    {
      title: 'My boss and my team',
      summary: 'Люди на работе.',
      topics: [W, D],
      dialogue: ['Про команду', [
        ['Anna', 'How many people are in your team?', 'Сколько человек в твоей команде?'],
        ['Ben', 'Six, and one boss.', 'Шесть и один начальник.'],
        ['Anna', 'Is he strict?', 'Он строгий?'],
        ['Ben', 'She. And no, she is fair.', 'Она. И нет, она справедливая.'],
        ['Anna', 'That is lucky.', 'Это удача.'],
      ]],
      words: [
        ['a boss', 'начальник', 'My boss is fair.'],
        ['a team', 'команда', 'A team of six.'],
        ['strict', 'строгий', 'Is he strict?'],
        ['fair', 'справедливый', 'She is fair.'],
        ['a colleague', 'коллега', 'A good colleague.'],
      ],
      rule: ['Boss не имеет рода', 'Boss, doctor, teacher, driver — все эти слова одинаковы для мужчин и женщин. Род показывает только местоимение: my boss — she is fair. Отдельных «женских» форм в современном английском почти не осталось.'],
      quiz: [
        ['«Мой начальник — она» —', ['My boss — she is fair', 'My bosswoman is fair', 'My boss she are fair'], 0],
        ['«Он строгий?» —', ['Is he strict?', 'Is he a strict?', 'He is strict it?'], 0],
        ['«Команда из шести человек» —', ['A team of six', 'A team from six', 'A six of team'], 0],
      ],
      order: ['Сколько человек в твоей команде?', 'How many people are in your team?'],
      produce: [
        ['Мой начальник справедливый.', 'My boss is fair.', []],
        ['Шесть и один начальник.', 'Six, and one boss.', []],
        ['Он строгий?', 'Is he strict?', []],
      ],
    },
    {
      title: 'A meeting at ten',
      summary: 'Рабочие встречи.',
      topics: [W, M, 'a1-prepositions-time'],
      dialogue: ['Планёрка', [
        ['Anna', 'We have a meeting at ten.', 'У нас встреча в десять.'],
        ['Ben', 'How long is it?', 'Сколько она длится?'],
        ['Anna', 'Half an hour, usually.', 'Обычно полчаса.'],
        ['Ben', 'Who comes?', 'Кто будет?'],
        ['Anna', 'The whole team and the boss.', 'Вся команда и начальник.'],
      ]],
      words: [
        ['a meeting', 'встреча, планёрка', 'A meeting at ten.'],
        ['half an hour', 'полчаса', 'Half an hour, usually.'],
        ['the whole team', 'вся команда', 'The whole team comes.'],
        ['an agenda', 'повестка', 'What is on the agenda?'],
        ['take notes', 'записывать', 'I take notes.'],
      ],
      rule: ['Whole и all', 'The whole team — вся команда как единое целое. All the team — то же самое, но с упором на каждого. На A1 разница почти незаметна, а вот порядок слов важен: the whole team, но all the team.'],
      quiz: [
        ['«Вся команда» —', ['the whole team', 'the all team', 'whole the team'], 0],
        ['«Полчаса» —', ['half an hour', 'a half hour of', 'half of hour'], 0],
        ['«Я записываю» —', ['I take notes', 'I take a notes', 'I make notes down'], 0],
      ],
      order: ['У нас встреча в десять.', 'We have a meeting at ten.'],
      produce: [
        ['У нас встреча в десять.', 'We have a meeting at ten.', []],
        ['Обычно полчаса.', 'Half an hour, usually.', []],
        ['Вся команда и начальник.', 'The whole team and the boss.', []],
      ],
    },
    {
      title: 'Sending an email',
      summary: 'Деловое письмо в три строки.',
      topics: [W, CON],
      dialogue: ['Письмо', [
        ['Anna', 'I send you the report today.', 'Отправлю тебе отчёт сегодня.'],
        ['Ben', 'Thanks. To my work email?', 'Спасибо. На рабочую почту?'],
        ['Anna', 'Yes. Do you need the numbers too?', 'Да. Цифры тоже нужны?'],
        ['Ben', 'Yes, please. And copy Maria.', 'Да, пожалуйста. И поставь Марию в копию.'],
        ['Anna', 'Will do.', 'Сделаю.'],
      ]],
      words: [
        ['send', 'отправить', 'I send the report today.'],
        ['a report', 'отчёт', 'The report is ready.'],
        ['copy', 'поставить в копию', 'Copy Maria, please.'],
        ['numbers', 'цифры, данные', 'Do you need the numbers?'],
        ['Will do.', 'Сделаю.', 'Will do, no problem.'],
      ],
      rule: ['Деловое письмо коротко', 'Hi Ben — одна строка сути — thanks, Anna. Длинные вступления в английской деловой переписке не приняты, а «уважаемый» и «с наилучшими пожеланиями» оставляют для официальных писем.'],
      quiz: [
        ['«Поставь Марию в копию» —', ['Copy Maria, please', 'Make a copy to Maria', 'Copy to Maria it please'], 0],
        ['«Отправлю сегодня» —', ['I send it today', 'I am send it today', 'I send today it will'], 0],
        ['«Сделаю» —', ['Will do', 'Will make', 'I will do it make'], 0],
      ],
      order: ['Отправлю тебе отчёт сегодня.', 'I send you the report today.'],
      produce: [
        ['Отправлю отчёт сегодня.', 'I send the report today.', []],
        ['Цифры тоже нужны?', 'Do you need the numbers too?', []],
        ['И поставь Марию в копию.', 'And copy Maria.', []],
      ],
    },
    {
      title: 'I am on holiday',
      summary: 'Отпуск и выходные дни.',
      topics: [W, 'a1-tema-travel'],
      dialogue: ['В отпуске', [
        ['Ben', 'Where is Anna?', 'Где Анна?'],
        ['Коллега', 'She is on holiday until Monday.', 'Она в отпуске до понедельника.'],
        ['Ben', 'Who does her work?', 'Кто делает её работу?'],
        ['Коллега', 'Maria does.', 'Мария.'],
        ['Ben', 'Good, thank you.', 'Хорошо, спасибо.'],
      ]],
      words: [
        ['on holiday', 'в отпуске', 'She is on holiday.'],
        ['until Monday', 'до понедельника', 'On holiday until Monday.'],
        ['a day off', 'выходной', 'I have a day off.'],
        ['cover', 'подменять', 'Maria covers for her.'],
        ['Maria does.', 'Мария.', 'Who does it? — Maria does.'],
      ],
      rule: ['Ответ вспомогательным глаголом', 'Who does her work — Maria does. Английский не повторяет глагол целиком, а ставит does, do или is. Это звучит естественно и коротко, а повтор всей фразы выдаёт учебник.'],
      quiz: [
        ['Ответ на who does her work:', ['Maria does', 'Maria do', 'Maria does her work does'], 0],
        ['«Она в отпуске» —', ['She is on holiday', 'She is in holiday', 'She is on a holiday'], 0],
        ['«У меня выходной» —', ['I have a day off', 'I have day off', 'I have an off day'], 0],
      ],
      order: ['Она в отпуске до понедельника.', 'She is on holiday until Monday.'],
      produce: [
        ['Она в отпуске.', 'She is on holiday.', []],
        ['У меня выходной.', 'I have a day off.', []],
        ['Мария её подменяет.', 'Maria covers for her.', []],
      ],
    },
    {
      title: 'Looking for a job',
      summary: 'Поиск работы и собеседование.',
      topics: [W, 'a1-present-continuous', Q],
      dialogue: ['Ищу работу', [
        ['Anna', 'I am looking for a new job.', 'Я ищу новую работу.'],
        ['Ben', 'In the same field?', 'В той же сфере?'],
        ['Anna', 'Yes, but a bigger company.', 'Да, но в компании побольше.'],
        ['Ben', 'Do you have an interview?', 'Собеседование есть?'],
        ['Anna', 'On Thursday. Wish me luck!', 'В четверг. Пожелай удачи!'],
      ]],
      words: [
        ['look for a job', 'искать работу', 'I am looking for a job.'],
        ['an interview', 'собеседование', 'An interview on Thursday.'],
        ['a field', 'сфера', 'In the same field.'],
        ['experience', 'опыт', 'Five years of experience.'],
        ['Wish me luck!', 'Пожелай удачи!', 'Interview tomorrow. Wish me luck!'],
      ],
      rule: ['Experience не считают', 'Experience — «опыт» вообще: a lot of experience, five years of experience. Множественное experiences значит «впечатления, случаи из жизни» — совсем другое слово по смыслу.'],
      quiz: [
        ['«Много опыта» —', ['a lot of experience', 'a lot of experiences', 'many experience'], 0],
        ['«Я ищу новую работу» —', ['I am looking for a new job', 'I look for new job now am', 'I am looking a new job'], 0],
        ['«Пожелай удачи» —', ['Wish me luck', 'Wish to me luck', 'Wish me a lucky'], 0],
      ],
      order: ['Я ищу новую работу.', 'I am looking for a new job.'],
      produce: [
        ['Я ищу новую работу.', 'I am looking for a new job.', ["I'm looking for a new job."]],
        ['Собеседование в четверг.', 'An interview on Thursday.', []],
        ['Пожелай удачи!', 'Wish me luck!', []],
      ],
    },
    {
      title: 'I can use a computer',
      summary: 'Навыки и умения.',
      topics: [W, C],
      dialogue: ['Что умеешь', [
        ['Интервьюер', 'Can you use Excel?', 'Умеете работать в Excel?'],
        ['Anna', 'Yes, well. And I can drive.', 'Да, хорошо. И вожу машину.'],
        ['Интервьюер', 'Do you speak other languages?', 'Другие языки знаете?'],
        ['Anna', 'English and a little Spanish.', 'Английский и немного испанский.'],
        ['Интервьюер', 'Very good.', 'Очень хорошо.'],
      ]],
      words: [
        ['use', 'пользоваться', 'Can you use Excel?'],
        ['drive', 'водить машину', 'I can drive.'],
        ['a skill', 'навык', 'A useful skill.'],
        ['other languages', 'другие языки', 'Do you speak other languages?'],
        ['a little Spanish', 'немного испанский', 'English and a little Spanish.'],
      ],
      rule: ['Can без to', 'I can drive, I can use, I can speak — после can глагол идёт голым. Ошибка I can to drive — калька с русского «я могу водить», где инфинитив нужен. По-английски он лишний.'],
      quiz: [
        ['«Я умею водить» —', ['I can drive', 'I can to drive', 'I can driving'], 0],
        ['«Умеете работать в Excel?» —', ['Can you use Excel?', 'Can you to use Excel?', 'Do you can use Excel?'], 0],
        ['«Немного испанский» —', ['a little Spanish', 'a few Spanish', 'a little of Spanish'], 0],
      ],
      order: ['Я умею водить машину.', 'I can drive a car.'],
      produce: [
        ['Я умею водить.', 'I can drive.', []],
        ['Умеете работать в Excel?', 'Can you use Excel?', []],
        ['Английский и немного испанский.', 'English and a little Spanish.', []],
      ],
    },
    {
      title: 'What time do you finish?',
      summary: 'Рабочие часы и переработки.',
      topics: [W, PS, Q],
      dialogue: ['До скольких', [
        ['Ben', 'What time do you finish?', 'Во сколько заканчиваешь?'],
        ['Anna', 'At six, usually.', 'Обычно в шесть.'],
        ['Ben', 'And today?', 'А сегодня?'],
        ['Anna', 'Later. We have a deadline.', 'Позже. У нас дедлайн.'],
        ['Ben', 'Good luck with that.', 'Удачи с этим.'],
      ]],
      words: [
        ['finish', 'заканчивать', 'I finish at six.'],
        ['a deadline', 'срок сдачи', 'We have a deadline.'],
        ['work late', 'работать допоздна', 'I work late today.'],
        ['overtime', 'переработка', 'Overtime is paid.'],
        ['Good luck with that.', 'Удачи с этим.', 'A deadline? Good luck with that.'],
      ],
      rule: ['Работа как расписание', 'I finish at six, I start at nine, I work from nine to six — простое время, потому что речь о постоянном порядке. Сегодняшнее исключение уходит в другое время: today I am working late.'],
      quiz: [
        ['«Во сколько заканчиваешь?» —', ['What time do you finish?', 'What time you finish?', 'What time are you finish?'], 0],
        ['«Сегодня работаю допоздна» —', ['Today I am working late', 'Today I work late am', 'Today I working late'], 0],
        ['«У нас дедлайн» —', ['We have a deadline', 'We have deadline', 'We are have a deadline'], 0],
      ],
      order: ['Обычно я заканчиваю в шесть.', 'I usually finish at six.'],
      produce: [
        ['Во сколько заканчиваешь?', 'What time do you finish?', []],
        ['Обычно в шесть.', 'At six, usually.', []],
        ['Сегодня работаю допоздна.', 'Today I am working late.', ["Today I'm working late."]],
      ],
    },
    {
      title: 'I like my job because…',
      summary: 'Сказать, что нравится и что нет.',
      topics: [W, D, 'a1-tema-leisure'],
      dialogue: ['Нравится ли работа', [
        ['Ben', 'Do you like your job?', 'Тебе нравится работа?'],
        ['Anna', 'Yes, because the team is good.', 'Да, потому что команда хорошая.'],
        ['Ben', 'And the bad part?', 'А плохая часть?'],
        ['Anna', 'Too many emails.', 'Слишком много писем.'],
        ['Ben', 'Same everywhere.', 'Везде так.'],
      ]],
      words: [
        ['because', 'потому что', 'Because the team is good.'],
        ['too many', 'слишком много', 'Too many emails.'],
        ['the bad part', 'плохая часть', 'And the bad part?'],
        ['interesting', 'интересный', 'The work is interesting.'],
        ['boring', 'скучный', 'The reports are boring.'],
      ],
      rule: ['Too many и too much', 'Too many с тем, что считают: too many emails, too many meetings. Too much с тем, что не считают: too much work, too much time. Ошибка too much emails слышна сразу.'],
      quiz: [
        ['«Слишком много писем» —', ['too many emails', 'too much emails', 'too many email'], 0],
        ['«Слишком много работы» —', ['too much work', 'too many work', 'too much works'], 0],
        ['«Работа интересная» —', ['The work is interesting', 'The work is interested', 'The work interests'], 0],
      ],
      order: ['Да, потому что команда хорошая.', 'Yes, because the team is good.'],
      produce: [
        ['Тебе нравится работа?', 'Do you like your job?', []],
        ['Слишком много писем.', 'Too many emails.', []],
        ['Работа интересная.', 'The work is interesting.', []],
      ],
    },
    {
      title: 'Working from home',
      summary: 'Удалёнка и офис.',
      topics: [W, 'a1-tema-home', PS],
      dialogue: ['Из дома', [
        ['Anna', 'Do you work from home?', 'Ты работаешь из дома?'],
        ['Ben', 'Two days a week.', 'Два дня в неделю.'],
        ['Anna', 'Which days?', 'В какие дни?'],
        ['Ben', 'Tuesday and Thursday.', 'Вторник и четверг.'],
        ['Anna', 'That is a good balance.', 'Хороший баланс.'],
      ]],
      words: [
        ['work from home', 'работать из дома', 'I work from home on Tuesday.'],
        ['two days a week', 'два дня в неделю', 'Two days a week.'],
        ['a balance', 'баланс', 'A good balance.'],
        ['an office day', 'офисный день', 'Monday is an office day.'],
        ['a video call', 'видеозвонок', 'A video call at ten.'],
      ],
      rule: ['From home, а не at home', 'Work from home — про способ работы. Be at home — про место, где вы сейчас. Обе фразы верны, но означают разное: I am at home today не обязательно значит, что вы работаете.'],
      quiz: [
        ['«Работать из дома» —', ['work from home', 'work at home from', 'work in home'], 0],
        ['«Два дня в неделю» —', ['two days a week', 'two days in week', 'two day a week'], 0],
        ['«Видеозвонок в десять» —', ['a video call at ten', 'a video call in ten', 'a call of video at ten'], 0],
      ],
      order: ['Я работаю из дома два дня в неделю.', 'I work from home two days a week.'],
      produce: [
        ['Ты работаешь из дома?', 'Do you work from home?', []],
        ['Два дня в неделю.', 'Two days a week.', []],
        ['Видеозвонок в десять.', 'A video call at ten.', []],
      ],
    },
    {
      title: 'Money and pay',
      summary: 'Зарплата — и как о ней не спрашивают.',
      topics: [W, 'a1-tema-shopping'],
      dialogue: ['Про деньги', [
        ['Ben', 'Is the pay good there?', 'Там хорошо платят?'],
        ['Anna', 'Not bad, and they pay on time.', 'Неплохо, и платят вовремя.'],
        ['Ben', 'That is important.', 'Это важно.'],
        ['Anna', 'More important than the money, sometimes.', 'Иногда важнее самих денег.'],
        ['Ben', 'True.', 'Верно.'],
      ]],
      words: [
        ['pay', 'зарплата; платить', 'Is the pay good?'],
        ['a salary', 'зарплата', 'A good salary.'],
        ['on time', 'вовремя', 'They pay on time.'],
        ['important', 'важный', 'That is important.'],
        ['True.', 'Верно.', 'True, I agree.'],
      ],
      rule: ['О зарплате не спрашивают прямо', 'How much do you earn — вопрос почти неприличный. Спрашивают обходно: is the pay good, is it well paid. И отвечают так же обтекаемо: not bad, it is fine.'],
      quiz: [
        ['«Там хорошо платят?» —', ['Is the pay good there?', 'Is the pay good it there?', 'How much they pay there?'], 0],
        ['«Платят вовремя» —', ['They pay on time', 'They pay in time', 'They are pay on time'], 0],
        ['Прямой вопрос о зарплате —', ['почти неприличен', 'обычное дело', 'признак вежливости'], 0],
      ],
      order: ['Неплохо, и платят вовремя.', 'Not bad, and they pay on time.'],
      produce: [
        ['Там хорошо платят?', 'Is the pay good there?', []],
        ['Платят вовремя.', 'They pay on time.', []],
        ['Это важно.', 'That is important.', ["That's important."]],
      ],
    },
    {
      title: 'Telling about your work',
      summary: 'Весь блок: рассказ о работе в пять предложений.',
      topics: [W, PS, D],
      dialogue: ['Рассказ целиком', [
        ['Anna', 'I work in a small company in the centre.', 'Я работаю в небольшой компании в центре.'],
        ['Ben', 'What do you do exactly?', 'Чем именно занимаешься?'],
        ['Anna', 'I answer emails and write reports.', 'Отвечаю на письма и пишу отчёты.'],
        ['Ben', 'Do you like it?', 'Нравится?'],
        ['Anna', 'Yes, the team is good and they pay on time.', 'Да, команда хорошая и платят вовремя.'],
      ]],
      words: [
        ['a small company', 'небольшая компания', 'I work in a small company.'],
        ['in the centre', 'в центре', 'A company in the centre.'],
        ['every day the same', 'каждый день одно и то же', 'Not every day the same.'],
        ['I enjoy it.', 'Мне нравится.', 'I enjoy it, honestly.'],
        ['a career', 'карьера', 'A good career.'],
      ],
      rule: ['Рассказ о работе — пять предложений', 'Где работаю → чем занимаюсь → с кем → сколько по времени → нравится или нет. Столько же нужно и на собеседовании, и в разговоре с новым знакомым: длиннее никто не слушает.'],
      quiz: [
        ['«Мне нравится» (о работе) —', ['I enjoy it', 'I enjoy of it', 'I am enjoy it'], 0],
        ['«В небольшой компании в центре» —', ['in a small company in the centre', 'in small company in centre', 'in a small company of the centre'], 0],
        ['«Не каждый день одно и то же» —', ['Not every day the same', 'Not all days the same it', 'No every day is same'], 0],
      ],
      order: ['Я работаю в небольшой компании в центре.', 'I work in a small company in the centre.'],
      produce: [
        ['Я работаю в небольшой компании.', 'I work in a small company.', []],
        ['Отвечаю на письма и пишу отчёты.', 'I answer emails and write reports.', []],
        ['Команда хорошая.', 'The team is good.', []],
      ],
    },
    {
      checkpoint: true,
      title: 'Проверка: работа',
      summary: 'Шесть фраз без подсказок — весь блок целиком.',
      topics: [W, PS, Q, C],
      produce: [
        ['Он работает в офисе.', 'He works in an office.', []],
        ['Он здесь работает?', 'Does he work here?', []],
        ['Она не работает по пятницам.', 'She does not work on Fridays.', ["She doesn't work on Fridays."]],
        ['Моя сестра медсестра.', 'My sister is a nurse.', []],
        ['У нас встреча в десять.', 'We have a meeting at ten.', []],
        ['Я умею водить.', 'I can drive.', []],
      ],
    },
  ],
}
